---
title: "GLM Proportion Simulation"
author: "Jeffrey Walker"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(MASS)
library(glmmTMB)
library(SimMultiCorrData) # correlated random negbin variables
library(sandwich) #robust cov

library(knitr)
library(kableExtra)
ggplot_the_model_path <- here::here("R/ggplot_the_model.R")
source(ggplot_the_model_path)

```

```{r rqpois}
  rqpois <- function(n, mu, theta) {
    # theta is the qp dispersion parameter which > 1
    # theta = 1 = poisson
    y <- rnbinom(n = n, mu = mu, size = mu/(theta-1))
    return(y)
  }
```


```{r fqaic}
fqaic <- function(model) {
  loglik <- sum(dpois(model$y, model$fitted.values, log = TRUE))
  phi <- summary(model)$dispersion
  qaic <- -2*loglik/phi + 2*summary(model)$df[3]
  qaic <- -2*loglik + 2*summary(model)$df[3] * phi
  return(qaic)
}
```


```{r pless, echo=FALSE}
  pless <- function(x){
    value <- sum(x < 0.05, na.rm=TRUE)/length(na.omit(x))
    return(value)
  }

```


```{r simulation-3x, fig.width=8, fig.height = 4, warning=FALSE}
# https://stats.stackexchange.com/questions/71519/when-do-poisson-and-negative-binomial-regressions-fit-the-same-coefficients
n_iter <- 2000
seed_starter <- 1
file_path <- "glm_proportion_results_out.Rds"
do_it <- TRUE
if(do_it){
  # proportions for power contrast
  prop_3_mag <- c(0.26, 0.16, 0.17, 0.13) # cor = .72
  prop_3_mag <- c(0.26, 0.16, 0.14, 0.17, 0.13, 0.12) # rho = .33
  prop_3_mag <- c(0.22, 0.15, 0.14, 0.14, 0.12, 0.12) # rho = .33
  prop_3_mag <- c(0.22, 0.155, 0.14, 0.155, 0.125, 0.12) # rho = .33

  # variable parameters
  model_list <- c("qp", "nb") # generating model for count data
  model_list <- c("nb") # need to find a general code for qp
  n_list <- c(6, 20)
  theta_list <- c(3, 12, 40)
  unbalanced <- FALSE    
  parameter_matrix <- expand.grid(theta = theta_list,
                                  model = model_list,
                                  sample_size = n_list)
  results_out <- data.table(NULL)
  
  mu_sim <- 2600
  theta_other <- 22
  k <- 3
  # note - power increases with r
  rho <- 0.33
  rho_matrix <- diag(6)
  rho_matrix[1,2] <- rho_matrix[2,1] <- rho
  rho_matrix[4,3] <- rho_matrix[3,4] <- rho
  rho_matrix[6,5] <- rho_matrix[5,6] <- rho
  
  stats_labels <- c("mw", "lm", "binom", "qb", "qbw", "qp", "nb2")
  # stats_labels <- c("mw", "lm", "binom", "qb", "qbw", "qp", "nb1", "nb2",
  #                   "nb1_pw", "nb1_pw_lrt", "nb2_pw", "nb2_pw_lrt")
 
  type1_matrix <- matrix(nrow = n_iter,
                         ncol = length(stats_labels))
  power_matrix <- matrix(nrow = n_iter,
                         ncol = length(stats_labels))
  colnames(type1_matrix) <- stats_labels
  colnames(power_matrix) <- stats_labels
  
  for(parameter_set in 1:nrow(parameter_matrix)){
    # if(parameter_set %in% c(1:4,6:8)){
    #   next()
    # }
    gen_theta <- parameter_matrix[parameter_set, "theta"]
    gen_model <- parameter_matrix[parameter_set, "model"]
    n <- parameter_matrix[parameter_set, "sample_size"]
    
    prop_sim <- c(0.1, 0.1, 0.2)
    prop_sim[3] <- prop_3_mag[parameter_set]

    mu_total <- c(mu_sim, mu_sim, mu_sim)
    mu_ctla4 <- prop_sim * mu_total # mu of cells expressing some marker
    mu_other <- (1 - prop_sim) * mu_total # mu of non marker cells
    
    row_i <- row.names(parameter_matrix)[parameter_set]

    if(unbalanced == TRUE){
      if(n == 6){
        n_vec <- c(4,6,8)
      }
      if(n == 20){
        n_vec <- c(14,20,26)
      }
    }else{
      n_vec <- c(n, n, n)
    }
    N <- sum(n_vec)
    fd <- data.table(
      genotype = rep(c("WT", "KO", "TR"), n_vec) |>
        factor(levels = c("WT", "KO", "TR"))
    )

    # nb var = mu + mu^2/theta
    # qp var = theta*mu
    # qp*mu = mu + mu^2/nb
    # qp = mu/mu + mu^2/nb
    # qp = 1 + mu/nb
    # if nb = 0.5 qp and mu = 10 then qp = 21
    # if nb = 2 qp and mu = 10 then qp = 6
    theta_nb <- gen_theta
    theta_qp <- 1 + mu_ctla4/theta_nb # for generating data each group has its own theta
    if(gen_model == "qp"){
      # numerator count
      y_qp <- rqpois(n * k * n_iter,
                     mu = rep(mu_ctla4, n_vec),
                     theta = theta_qp[1]
                     )
      y_mat <- matrix(y_qp, nrow = n * k, ncol = n_iter)
    }
    if(gen_model == "nb"){
      fake_y <- rcorrvar(n = n * n_iter,
                         mu = c(mu_ctla4[1], mu_other[1],
                                mu_ctla4[2], mu_other[2],
                                mu_ctla4[3], mu_other[3]),
                         k_nb = 6,
                         size = rep(c(theta_nb, theta_other), 3),
                         rho = rho_matrix,
                         seed = seed_starter)$Neg_Bin_variables
      ctla4_mat_cn <- matrix(fake_y[,1], nrow = n, ncol = n_iter)
      other_mat_cn <- matrix(fake_y[,2], nrow = n, ncol = n_iter)
      ctla4_mat_ko <- matrix(fake_y[,3], nrow = n, ncol = n_iter)
      other_mat_ko <- matrix(fake_y[,4], nrow = n, ncol = n_iter)
      ctla4_mat_tr <- matrix(fake_y[,5], nrow = n, ncol = n_iter)
      other_mat_tr <- matrix(fake_y[,6], nrow = n, ncol = n_iter)
      total_mat_cn <- ctla4_mat_cn + other_mat_cn
      total_mat_ko <- ctla4_mat_ko + other_mat_ko
      total_mat_tr <- ctla4_mat_tr + other_mat_tr
      proportion_mat_cn <- ctla4_mat_cn/total_mat_cn
      proportion_mat_ko <- ctla4_mat_ko/total_mat_ko
      proportion_mat_tr <- ctla4_mat_tr/total_mat_tr
      ctla4_mat <- rbind(ctla4_mat_cn, ctla4_mat_ko, ctla4_mat_tr)
      total_mat <- rbind(total_mat_cn, total_mat_ko, total_mat_tr)
      
      apply(proportion_mat_cn, 2, mean) |> mean()
      apply(proportion_mat_ko, 2, mean) |> mean()
      apply(proportion_mat_tr, 2, mean) |> mean()
      # cor(fake_y)
      # fake_y$total1 <- fake_y$V1 + fake_y$V2
      # fake_y$prop1 <- fake_y$V1/fake_y$total1
      # mean(fake_y$prop1)
      # fake_y$total2 <- fake_y$V3 + fake_y$V4
      # fake_y$prop2 <- fake_y$V3/fake_y$total2
      # mean(fake_y$prop2)
    }
    
    for(iter in 1:n_iter){
      fd[, ctla4 := ctla4_mat[, iter]]
      fd[, total := total_mat[, iter]]
      fd[, proportion := ctla4/total]
      
      # Mann-Whitney-Wilcoxan
      mww1 <- wilcox.test(proportion ~ genotype,
                          data = fd[genotype %in% c("WT", "KO"),])$p.value
      mww2 <- wilcox.test(proportion ~ genotype,
                          data = fd[genotype %in% c("WT", "TR"),])$p.value
      # lm
      lm1 <- lm(proportion ~ genotype,
                data = fd)
      
      # binomial
      bin1 <- glm(proportion ~ genotype,
                 family = binomial,
                 weights = total,
                 data = fd)
      qb1 <- glm(proportion ~ genotype,
                 family = quasibinomial,
                 data = fd)
      qbw <- glm(proportion ~ genotype,
                 family = quasibinomial,
                 weights = total,
                 data = fd)
      # count models
      qp1 <- glm(proportion ~ genotype,
                 family = quasipoisson(link = "log"),
                 data = fd)
      # nb1 <- glmmTMB(proportion*100 ~ genotype,
      #                family = nbinom1(link = "log"),
      #                data = fd)
      nb2 <- glmmTMB(proportion*100 ~ genotype,
                     family = nbinom2(link = "log"),
                     data = fd)
      # # pairwise models
      # nb1_pw_1 <- glmmTMB(proportion*100 ~ genotype,  # the type 1 pair
      #                     family = nbinom1(link = "log"),
      #                     data = fd[genotype %in% c("WT", "KO"),])
      # nb1_pw_2 <- glmmTMB(proportion*100 ~ genotype,  # the power pair
      #                     family = nbinom1(link = "log"),
      #                     data = fd[genotype %in% c("WT", "TR"),])
      # nb2_pw_1 <- glmmTMB(proportion*100 ~ genotype,  # the type 1 pair
      #                     family = nbinom2(link = "log"),
      #                     data = fd[genotype %in% c("WT", "KO"),])
      # nb2_pw_2 <- glmmTMB(proportion*100 ~ genotype,  # the power pair
      #                     family = nbinom2(link = "log"),
      #                     data = fd[genotype %in% c("WT", "TR"),])
      # 
      # type 1
      nonref <- 2
      type1_matrix[iter, "mw"] <- mww1
      type1_matrix[iter, "lm"] <- summary(contrast(emmeans(lm1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      type1_matrix[iter, "binom"] <- summary(contrast(emmeans(bin1,
                                                             specs = "genotype",
                                                             vcov. = vcovHC(qb1, type="HC3")),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      type1_matrix[iter, "qb"] <- summary(contrast(emmeans(qb1,
                                                             specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      type1_matrix[iter, "qbw"] <- summary(contrast(emmeans(qbw,
                                                              specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      type1_matrix[iter, "qp"] <- summary(contrast(emmeans(qp1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      # type1_matrix[iter, "nb1"] <- summary(contrast(
      #   emmeans(nb1, specs = "genotype"), method = "revpairwise",
      #   adjust = "none"))[nonref-1,"p.value"]
      # 
      type1_matrix[iter, "nb2"] <- summary(contrast(
        emmeans(nb2, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[nonref-1,"p.value"]

      # type1_matrix[iter, "nb1_pw"] <- summary(contrast(
      #   emmeans(nb1_pw_1, specs = "genotype"), method = "revpairwise",
      #   adjust = "none"))[1,"p.value"]
      # type1_matrix[iter, "nb1_pw_lrt"] <- drop1(nb1_pw_1, test="Chisq")$"Pr(>Chi)"[2]
      # 
      # type1_matrix[iter, "nb2_pw"] <- summary(contrast(
      #   emmeans(nb2_pw_1, specs = "genotype"), method = "revpairwise",
      #   adjust = "none"))[1,"p.value"]
      # type1_matrix[iter, "nb2_pw_lrt"] <- drop1(nb2_pw_1, test="Chisq")$"Pr(>Chi)"[2]
      

      # power
      nonref <- 3
      power_matrix[iter, "mw"] <- mww2
      power_matrix[iter, "lm"] <- summary(contrast(emmeans(lm1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      power_matrix[iter, "binom"] <- summary(contrast(emmeans(bin1,
                                                            specs = "genotype",
                                                            vcov. = vcovHC(qb1, type="HC3")),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      power_matrix[iter, "qb"] <- summary(contrast(emmeans(qb1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      power_matrix[iter, "qbw"] <- summary(contrast(emmeans(qbw,
                                                            specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      power_matrix[iter, "qp"] <- summary(contrast(emmeans(qp1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      # power_matrix[iter, "nb1"] <- summary(contrast(
      #   emmeans(nb1, specs = "genotype"), method = "revpairwise",
      #   adjust = "none"))[nonref-1,"p.value"]
      # 
      power_matrix[iter, "nb2"] <- summary(contrast(
        emmeans(nb2, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[nonref-1,"p.value"]

      # power_matrix[iter, "nb1_pw"] <- summary(contrast(
      #   emmeans(nb1_pw_2, specs = "genotype"), method = "revpairwise",
      #   adjust = "none"))[1,"p.value"]
      # power_matrix[iter, "nb1_pw_lrt"] <- drop1(nb1_pw_2,
      #                                             test="Chisq")$"Pr(>Chi)"[2]
      # 
      # power_matrix[iter, "nb2_pw"] <- summary(contrast(
      #   emmeans(nb2_pw_2, specs = "genotype"), method = "revpairwise",
      #   adjust = "none"))[1,"p.value"]
      # power_matrix[iter, "nb2_pw_lrt"] <- drop1(nb2_pw_2,
      #                                             test="Chisq")$"Pr(>Chi)"[2]
      # 
      
    }
    results_out <- rbind(
      results_out,
      data.table(
        theta = gen_theta,
        model = gen_model,
        sample_size = n,
        prop_ref = prop_sim[1],
        prop_tr = prop_sim[2],
        "rho" = rho,
        type = "type1",
        type1_matrix
      ),
      data.table(
        theta = gen_theta,
        model = gen_model,
        sample_size = n,
        prop_ref = prop_sim[1],
        prop_tr = prop_sim[3],
        "rho" = rho,
        type = "power",
        power_matrix
      )
    )
  }
  
  saveRDS(results_out, file_path)
  
}


results_out <- readRDS(file_path)
# results_out <- readRDS("glm_3x_results_balanced.Rds")


# print results
type_list <- c("type1", "power")
  
parameter_matrix <- expand.grid(theta = theta_list,
                                model = model_list,
                                sample_size = n_list,
                                sim_type = type_list)

# stats_labels <- c("lm", "qb", "rqb", "qp", "nb1", "nb2",
#                     "nb1_pw", "nb1_pw_lrt", "nb2_pw", "nb2_pw_lrt", "mw")
  
stats_matrix <- matrix(nrow = n_iter,
                       ncol = length(stats_labels))
colnames(stats_matrix) <- stats_labels

summary_table <- data.table(NULL)
for(parameter_set in 1:nrow(parameter_matrix)){
  gen_theta <- parameter_matrix[parameter_set, "theta"]
  gen_model <- parameter_matrix[parameter_set, "model"]
  sim_type <- parameter_matrix[parameter_set, "sim_type"]
  n <- parameter_matrix[parameter_set, "sample_size"] 
  stats_matrix <- results_out[theta == gen_theta & 
                                model == gen_model &
                                type == sim_type &
                                sample_size == n,
                              .SD,
                              .SDcols = stats_labels] |>
    as.matrix()
    stats_matrix <- results_out[theta == gen_theta & 
                                model == gen_model &
                                type == sim_type &
                                sample_size == n,
                              .SD,
                              .SDcols = stats_labels] |>
    as.matrix()

  
  mw_pless <- pless(stats_matrix[, "mw"])
  lm_pless <- pless(stats_matrix[, "lm"])
  binom_pless <- pless(stats_matrix[, "binom"])
  qb_pless <- pless(stats_matrix[, "qb"])
  qbw_pless <- pless(stats_matrix[, "qbw"])
  qp_pless <- pless(stats_matrix[, "qp"])
  # nb1_pless <- pless(stats_matrix[, "nb1"])
  nb2_pless <- pless(stats_matrix[, "nb2"])
  # nb1_pw_pless <- pless(stats_matrix[, "nb1_pw"])
  # nb2_pw_pless <- pless(stats_matrix[, "nb2_pw"])
  # nb1_pw_lrt_pless <- pless(stats_matrix[, "nb1_pw_lrt"])
  # nb2_pw_lrt_pless <- pless(stats_matrix[, "nb2_pw_lrt"])
  
  fit_models <- c("mw", "lm", "binom", "qb", "qbw", "qp", "nb2")
  # fit_models <- c("mw", "lm", "binom", "qb", "qbw", "qp", "nb1", "nb2",
  #                 "nb1_pw", "nb2_pw", "nb1_pw_lrt", "nb2_pw_lrt")

  # pless_vec <- c(mw_pless, lm_pless, binom_pless, qb_pless, qbw_pless,
  #                    qp_pless, nb1_pless, nb2_pless, 
  #                    nb1_pw_pless, nb2_pw_pless,
  #                    nb1_pw_lrt_pless, nb2_pw_lrt_pless)
  pless_vec <- c(mw_pless, lm_pless, binom_pless, qb_pless, qbw_pless,
                     qp_pless, nb2_pless)
  
  summary_table <- rbind(
    summary_table,
    data.table(
      "theta" = gen_theta,
      "gen_model" = gen_model,
      "n" = n,
      type = sim_type,
      "fit_model" = fit_models,
      "p < 0.05" = pless_vec
    )
  )
  
}


summary_table |>
  kable(digits = c(1,1,1,1,1,3,3,3,3,3,3)) |>
  kable_styling()

summary_table[, fit_model := factor(fit_model,
                                    levels = fit_models)]

heatmap_type1 <- summary_table[type == "type1"]
setnames(heatmap_type1, "p < 0.05", "type1")
heatmap_type1[, sim := paste(theta, gen_model, n, sep = "\n")]
heatmap_type1[, sim := factor(sim,
                              levels = unique(sim))]
heatmap_type1[, fit_model := factor(fit_model,
                                    levels = fit_models)]

heatmap_power <- summary_table[type == "power"]
setnames(heatmap_power, "p < 0.05", "power")
heatmap_power[, sim := paste(theta, gen_model, n, sep = "\n")]
heatmap_power[, sim := factor(sim,
                              levels = unique(sim))]
heatmap_power[, fit_model := factor(fit_model,
                                    levels = fit_models)]
sim_levels <- levels(heatmap_power$sim)


gg1 <- ggplot(data = heatmap_type1,
              aes(x = sim, y = fit_model, fill = type1)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue",
                       mid = "white",
                       high = "red",
                       midpoint = 0.05) +
  geom_text(aes(label = round(type1,3)), color = "black", size = 3) +
  labs(title = "Type 1",
       x = "Parameters",
       y = "Fit Model")

gg2 <- ggplot(data = heatmap_power,
              aes(x = sim, y = fit_model, fill = power)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#e5f5e0", # "#fee5d9"
                       high = "#238b45",
                       midpoint = median(heatmap_power[, power])) +
  geom_text(aes(label = round(power, 2)), color = "black", size = 3) +
  labs(title = "Power",
       x = "Parameters",
       y = "Fit Model")

# gg1
# gg2
plot_grid(gg1, gg2)
```

 ```{r combine-results_out}
balanced <- TRUE
if(balanced){
  unbalanced <- FALSE
}else{
  unbalanced <- TRUE
}
if(balanced){
  # unbalanced
  file1 <- readRDS("glm_3x_results_balanced 1000 seed 1.Rds")
  file2 <- readRDS("glm_3x_results_balanced 2000 seed 2.Rds")
  file3 <- readRDS("glm_3x_results_balanced 2000 seed 2.Rds")
  results_out <- rbind(file1, file2, file3)
  file_save <- "glm_3x_results_balanced.Rds"
}
if(unbalanced){
  # unbalanced
  file1 <- readRDS("glm_3x_results_unbalanced 2000 seed 1.Rds")
  file2 <- readRDS("glm_3x_results_unbalanced 3000 seed 2.Rds")
  results_out <- rbind(file1, file2)
  file_save <- "glm_3x_results_unbalanced.Rds"
}
#balanced

# resave
saveRDS(results_out, file_save)

```

```{r nb1-nb2-check}
# https://stats.stackexchange.com/questions/71519/when-do-poisson-and-negative-binomial-regressions-fit-the-same-coefficients
n_iter <- 10
set.seed(1)
file_path <- "glm_3x_nb1-nb2-check.Rds"
# variable parameters
model_list <- c("qp", "nb")
n_list <- c(6, 20)
theta_list <- c(1, 5)

parameter_matrix <- expand.grid(theta = theta_list,
                                model = model_list,
                                sample_size = n_list)


stats_labels <- c("qp_aic", "qp_unif", "qp_disp", "qp_xxx",
                  "nb1_aic", "nb1_unif", "nb1_disp", "nb1_xxx",
                  "nb2_aic", "nb2_unif", "nb2_disp", "nb2_xxx",
                  "nb1_pw_aic", "nb1_pw_unif", "nb1_pw_disp", "nb1_pw_xxx",
                  "nb2_pw_aic", "nb2_pw_unif", "nb2_pw_disp", "nb2_pw_xxx")
results_out <- data.table(NULL)

mag <- 1
mu_sim <- c(10^mag, 10^mag, 2*10^mag)
k <- length(mu_sim)


stats_matrix <- matrix(nrow = n_iter,
                       ncol = length(stats_labels))
colnames(stats_matrix) <- stats_labels

for(parameter_set in 1:nrow(parameter_matrix)){
  gen_theta <- parameter_matrix[parameter_set, "theta"]
  gen_model <- parameter_matrix[parameter_set, "model"]
  n <- parameter_matrix[parameter_set, "sample_size"]

  fd <- data.table(
    genotype = rep(c("WT", "KO", "TR"), each = n) |>
      factor(levels = c("WT", "KO", "TR"))
  )
  
  # nb var = mu + mu^2/theta
  # qp var = theta*mu
  # qp*mu = mu + mu^2/nb
  # qp = mu/mu + mu^2/nb
  # qp = 1 + mu/nb
  # if nb = 0.5 qp and mu = 10 then qp = 21
  # if nb = 2 qp and mu = 10 then qp = 6
  theta_nb <- gen_theta
  theta_qp <- 1 + mu_sim/theta_nb # for generating data each group has its own theta
  if(gen_model == "qp"){
    y_qp <- rqpois(n * k * n_iter,
                   mu = rep(mu_sim, each = n),
                   theta = theta_qp[1])
    y_mat <- matrix(y_qp, nrow = n * k, ncol = n_iter)
  }
  if(gen_model == "nb"){
    y_nb <- rnegbin(n * k * n_iter,
                    mu = rep(mu_sim, each = n),
                    theta = theta_nb)
    y_mat <- matrix(y_nb, nrow = n * k, ncol = n_iter)
  }

  for(iter in 1:n_iter){
    fd[, tumors := y_mat[, iter]]
    qp1 <- glm(tumors ~ genotype,
               family = quasipoisson(link = "log"),
               data = fd)
    nb1 <- glmmTMB(tumors ~ genotype,
                   family = nbinom1(link = "log"),
                   data = fd)
    nb2 <- glmmTMB(tumors ~ genotype,
                  family = nbinom2(link = "log"),
                  data = fd)
    # pairwise
    nb1_pw_1 <- glmmTMB(tumors ~ genotype,  # the type 1 pair
                             family = nbinom1(link = "log"),
                             data = fd[genotype != "TR",])
    nb1_pw_2 <- glmmTMB(tumors ~ genotype,  # the power pair
                             family = nbinom1(link = "log"),
                             data = fd[genotype != "KO",])
    nb2_pw_1 <- glmmTMB(tumors ~ genotype,  # the type 1 pair
                             family = nbinom2(link = "log"),
                             data = fd[genotype != "TR",])
    nb2_pw_2 <- glmmTMB(tumors ~ genotype,  # the power pair
                             family = nbinom2(link = "log"),
                             data = fd[genotype != "KO",])
    aic_vals <- AIC(nb1, nb2)
    stats_matrix[iter, "nb1_aic"] <- aic_vals[1,2]
    stats_matrix[iter, "nb2_aic"] <- aic_vals[1,2]
    qp1_check <- ggcheck_the_glm(qp1, n_sim = 500)
    nb1_check <- ggcheck_the_glm(nb1, n_sim = 500)
    nb2_check <- ggcheck_the_glm(nb2, n_sim = 500)
    plot(qp1_check)
    plot(nb1_check)
    plot(nb2_check)
    stats_matrix[iter, "qp_unif"] <- testUniformity(qp1_check)$statistic
    stats_matrix[iter, "nb1_unif"] <- testUniformity(nb1_check)$statistic
    stats_matrix[iter, "nb2_unif"] <- testUniformity(nb2_check)$statistic
    stats_matrix[iter, "qp_disp"] <- testDispersion(qp1_check)$statistic
    stats_matrix[iter, "nb1_disp"] <- testDispersion(nb1_check)$statistic
    stats_matrix[iter, "nb2_disp"] <- testDispersion(nb2_check)$statistic
  }
  results_out <- rbind(
    results_out,
    data.table(
      theta = gen_theta,
      model = gen_model,
      sample_size = n,
      type = "type1",
      stats_matrix
    )
  )
}

saveRDS(results_out, file_path)
results_out <- readRDS(file_path)

results_out[, aic_nb2_nb1 := nb2_aic - nb1_aic] # if nb1 better, than this will be positive
results_out[, unif_nb2_nb1 := nb2_unif - nb1_unif] # if nb1 better, than this will be positive
results_out[, unif_nb2_qp1 := nb2_unif - qp_unif] # if qp better, than this will be positive
results_out[, unif_nb1_qp1 := nb1_unif - qp_unif] # if qp better, than this will be positive
results_out[, disp_nb2_qp1 := nb2_disp - nb1_disp] # if nb1 better, than this will be positive
ggplot(data = results_out[sample_size == 20],
       aes(x = model,
           y = aic_nb2_nb1)) +
  geom_jitter(width = 0.2)
ggplot(data = results_out[sample_size == 20],
       aes(x = model,
           y = unif_nb2_nb1)) +
  geom_jitter(width = 0.2)
ggplot(data = results_out[sample_size == 20],
       aes(x = model,
           y = unif_nb2_qp1)) +
  geom_jitter(width = 0.2)
ggplot(data = results_out[sample_size == 20],
       aes(x = model,
           y = unif_nb1_qp1)) +
  geom_jitter(width = 0.2)
ggplot(data = results_out[sample_size == 20],
       aes(x = model,
           y = disp_nb2_qp1)) +
  geom_jitter(width = 0.2)

```


```{r}
Tx=c('TS','TS','TS','TS','CT','CT','CT','CT','TS','TS','TS','TS','RL','RL','RL','RL','RT','RT','RT','RT','RL','RL','RT','RT','RT','RT','RL','RL','RL','RT','RT','RT','TS','TS','CT','CT','CT','CT','RL','RL','RL','RT','RT','RT','RT','CT','CT','CT','CT','CT','CT','TS','TS')
Bk= c('A','A','A','A','B','B','B','B','D','D','D','D','D','D','D','D','D','D','D','D','A','A','A','A','A','A','C','C','C','C','C', 'C','C','C','C','C','C','C','B','B','B','B','B','B','B','D','D','D','A','A','A','B','B')
Rv=c(2.08,2.08,2.52,3.42,2.8,5.57,2.53,3.69,1.55,1.45,3.98,3.19,2.3,2.09,2.26,2.1,3.21,2.99,2.11,2.09,1.64,1.74,1.66,6.41,1.86,2.71,1.83,0.86,2.37,1.05,1.37,2.08,1.09,1.44,0.6,1.24,3.32,1.34,1.86,4.54,2.7,2.5,4.93,2.85,3.42,2.77,2.71,4.11,5.29,2.16,3.15,4.58,2.89)
dat <- data.table(Tx, Bk, Rv)
lmm.ri <- lmer(Rv ~ Tx + (1 | Bk), data = dat)
lmm.ris <- lmer(Rv ~ Tx + (Tx | Bk), data = dat)
rmaov <- aov_4(Rv ~ Tx + (Tx | Bk),
               fun_aggregate = mean,
               data = dat)


contrast(emmeans(lmm.ri, specs = "Tx"), method = "revpairwise", adjust = "none")
contrast(emmeans(lmm.ris, specs = "Tx"), method = "revpairwise", adjust = "none")
contrast(emmeans(rmaov, specs = "Tx"), method = "revpairwise", adjust = "none")

VarCorr(lmm.ri)
VarCorr(lmm.ris)

lm1 <- lm(Rv ~ Tx, data = dat)
dat[, resid := residuals(lm1)]
dat_agg <- dat[, .(Rv = mean(Rv)), by = .(Tx, Bk)]
dat_agg_wide <- dcast(dat_agg, Bk ~ Tx, val.var = "Rv")
cor(dat_agg_wide[, .SD, .SDcols = c("A", "B", "C", "D")])
```

