<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.52">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; P-values – Statistics for the Experimental Bench Biologist</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/inference-errors.html" rel="next">
<link href="../chapters/uncertainty-sd-and-se.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/p-values.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">P-values</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Statistics for the Experimental Bench Biologist</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Analyzing experimental data with a linear model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started – R Projects and R Markdown</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/reading-writing-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data – Reading, Wrangling, and Writing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/plotting-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Plotting Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/uncertainty-sd-and-se.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Variability and Uncertainty (Standard Deviations, Standard Errors, and Confidence Intervals)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/p-values.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">P-values</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/inference-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Errors in inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro-stat-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">An introduction to linear models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/continuous_x.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Linear models with a single, continuous <em>X</em> (“linear regression”)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/one-factor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Linear models with a single, categorical <em>X</em> (“t-tests” and “ANOVA”)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/model-checking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Model checking</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multiple-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Multiple tests – why and when to adjust <em>p</em>-values</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/two-factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Linear models with two categorical <span class="math inline">\(X\)</span> – Factorial linear models (“two-way ANOVA”)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linear models with added covariates (“ANCOVA”)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/lmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Models for non-independence – linear mixed models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Models for counts, binary responses, skewed responses, and proportions – Generalized Linear Models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution" id="toc-a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution" class="nav-link active" data-scroll-target="#a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution"><span class="header-section-number">6.1</span> A <em>p</em>-value is the probability of sampling a value as or more extreme than the test statistic if sampling from a null distribution</a></li>
  <li><a href="#pump-your-intuition-creating-a-null-distribution" id="toc-pump-your-intuition-creating-a-null-distribution" class="nav-link" data-scroll-target="#pump-your-intuition-creating-a-null-distribution"><span class="header-section-number">6.2</span> Pump your intuition – Creating a null distribution</a></li>
  <li><a href="#a-null-distribution-of-t-values-the-t-distribution" id="toc-a-null-distribution-of-t-values-the-t-distribution" class="nav-link" data-scroll-target="#a-null-distribution-of-t-values-the-t-distribution"><span class="header-section-number">6.3</span> A null distribution of <em>t</em>-values – the <em>t</em> distribution</a></li>
  <li><a href="#p-values-from-the-perspective-of-permutation" id="toc-p-values-from-the-perspective-of-permutation" class="nav-link" data-scroll-target="#p-values-from-the-perspective-of-permutation"><span class="header-section-number">6.4</span> P-values from the perspective of permutation</a></li>
  <li><a href="#parametric-vs.-non-parametric-statistics" id="toc-parametric-vs.-non-parametric-statistics" class="nav-link" data-scroll-target="#parametric-vs.-non-parametric-statistics"><span class="header-section-number">6.5</span> Parametric vs.&nbsp;non-parametric statistics</a></li>
  <li><a href="#frequentist-probability-and-the-interpretation-of-p-values" id="toc-frequentist-probability-and-the-interpretation-of-p-values" class="nav-link" data-scroll-target="#frequentist-probability-and-the-interpretation-of-p-values"><span class="header-section-number">6.6</span> frequentist probability and the interpretation of p-values</a>
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><span class="header-section-number">6.6.1</span> Background</a></li>
  <li><a href="#this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability." id="toc-this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability." class="nav-link" data-scroll-target="#this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability."><span class="header-section-number">6.6.2</span> This book covers frequentist approaches to statistical modeling and when a probability arises, such as the <em>p</em>-value of a test statistic, this will be a frequentist probability.</a></li>
  <li><a href="#two-interpretations-of-the-p-value" id="toc-two-interpretations-of-the-p-value" class="nav-link" data-scroll-target="#two-interpretations-of-the-p-value"><span class="header-section-number">6.6.3</span> Two interpretations of the <em>p</em>-value</a></li>
  <li><a href="#nhst" id="toc-nhst" class="nav-link" data-scroll-target="#nhst"><span class="header-section-number">6.6.4</span> NHST</a></li>
  </ul></li>
  <li><a href="#some-major-misconceptions-of-the-p-value" id="toc-some-major-misconceptions-of-the-p-value" class="nav-link" data-scroll-target="#some-major-misconceptions-of-the-p-value"><span class="header-section-number">6.7</span> Some major misconceptions of the <em>p</em>-value</a>
  <ul>
  <li><a href="#misconception-p-0.05-means-there-is-no-effect-of-treatment" id="toc-misconception-p-0.05-means-there-is-no-effect-of-treatment" class="nav-link" data-scroll-target="#misconception-p-0.05-means-there-is-no-effect-of-treatment"><span class="header-section-number">6.7.1</span> Misconception: <span class="math inline">\(p &gt; 0.05\)</span> means there is no effect of treatment</a></li>
  <li><a href="#misconception-a-p-value-is-repeatable" id="toc-misconception-a-p-value-is-repeatable" class="nav-link" data-scroll-target="#misconception-a-p-value-is-repeatable"><span class="header-section-number">6.7.2</span> Misconception: a <em>p</em>-value is repeatable</a>
  <ul class="collapse">
  <li><a href="#the-incredible-inconsistency-of-the-p-value" id="toc-the-incredible-inconsistency-of-the-p-value" class="nav-link" data-scroll-target="#the-incredible-inconsistency-of-the-p-value"><span class="header-section-number">6.7.2.1</span> The incredible inconsistency of the <em>p</em>-value</a></li>
  <li><a href="#what-is-the-distribution-of-p-values-under-the-null" id="toc-what-is-the-distribution-of-p-values-under-the-null" class="nav-link" data-scroll-target="#what-is-the-distribution-of-p-values-under-the-null"><span class="header-section-number">6.7.2.2</span> What is the distribution of <em>p</em>-values under the null?</a></li>
  </ul></li>
  <li><a href="#misconception-0.05-is-the-lifetime-rate-of-false-discoveries" id="toc-misconception-0.05-is-the-lifetime-rate-of-false-discoveries" class="nav-link" data-scroll-target="#misconception-0.05-is-the-lifetime-rate-of-false-discoveries"><span class="header-section-number">6.7.3</span> Misconception: 0.05 is the lifetime rate of false discoveries</a></li>
  <li><a href="#misconception-a-low-p-value-indicates-an-important-effect" id="toc-misconception-a-low-p-value-indicates-an-important-effect" class="nav-link" data-scroll-target="#misconception-a-low-p-value-indicates-an-important-effect"><span class="header-section-number">6.7.4</span> Misconception: a low <em>p</em>-value indicates an important effect</a></li>
  <li><a href="#misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity" id="toc-misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity" class="nav-link" data-scroll-target="#misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity"><span class="header-section-number">6.7.5</span> Misconception: a low <em>p</em>-value indicates high model fit or high predictive capacity</a></li>
  </ul></li>
  <li><a href="#what-the-p-value-does-not-mean" id="toc-what-the-p-value-does-not-mean" class="nav-link" data-scroll-target="#what-the-p-value-does-not-mean"><span class="header-section-number">6.8</span> What the <em>p</em>-value does not mean</a></li>
  <li><a href="#on-using-p-values-in-experimental-biology" id="toc-on-using-p-values-in-experimental-biology" class="nav-link" data-scroll-target="#on-using-p-values-in-experimental-biology"><span class="header-section-number">6.9</span> On using <em>p</em>-values in experimental biology</a></li>
  <li><a href="#better-reproducibility" id="toc-better-reproducibility" class="nav-link" data-scroll-target="#better-reproducibility"><span class="header-section-number">6.10</span> Better reproducibility</a></li>
  <li><a href="#multiple-testing-and-controlling-for-false-positives" id="toc-multiple-testing-and-controlling-for-false-positives" class="nav-link" data-scroll-target="#multiple-testing-and-controlling-for-false-positives"><span class="header-section-number">6.11</span> Multiple testing and controlling for false positives</a>
  <ul>
  <li><a href="#controlling-the-family-wise-error-rate-when-all-tests-are-testing-the-same-hypothesis" id="toc-controlling-the-family-wise-error-rate-when-all-tests-are-testing-the-same-hypothesis" class="nav-link" data-scroll-target="#controlling-the-family-wise-error-rate-when-all-tests-are-testing-the-same-hypothesis"><span class="header-section-number">6.11.1</span> Controlling the family-wise error rate when all tests are testing the same hypothesis</a></li>
  </ul></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations"><span class="header-section-number">6.12</span> Recommendations</a>
  <ul>
  <li><a href="#primary-sources-for-recommendations" id="toc-primary-sources-for-recommendations" class="nav-link" data-scroll-target="#primary-sources-for-recommendations"><span class="header-section-number">6.12.1</span> Primary sources for recommendations</a></li>
  </ul></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems"><span class="header-section-number">6.13</span> Problems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-pvalues" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">P-values</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>A general perception of a “replication crisis” may thus reflect failure to recognize that statistical tests not only test hypotheses, but countless assumptions and the entire environment in which research takes place. Because of all the uncertain and unknown assumptions that underpin statistical inferences, we should treat inferential statistics as highly unstable local descriptions of relations between assumptions and data, rather than as providing generalizable inferences about hypotheses or models. And that means we should treat statistical results as being much more incomplete and uncertain than is currently the norm.</em><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>A <em>p</em>-value <em>is a measure of the compatibility between observed data and the null model</em>. Here, “compatibility” is a probability, specifically, the probability of sampling a test-statistic as or more extreme than the observed test statistic, if all the assumptions used to compute the <em>p</em>-value are true.</p>
<p>To deconstruct what this means, and the implications of the meaning, let’s use the fig2i data from Figure 2i in the study on the browning of white adipose tissue in mice that was introduced in <a href="../intro.html" class="quarto-xref"><span>Chapter 1</span></a></p>
<p>Data source: <a href="https://www.nature.com/articles/s41467-020-15483-7" target="_blank">ASK1 inhibits browning of white adipose tissue in obesity</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>fig2i_m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(liver_tg <span class="sc">~</span> treatment, <span class="at">data =</span> fig2i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The chunk above fits a linear model with <code>liver_tg</code> as the response variable and <code>treatment</code> as the single <span class="math inline">\(X\)</span>-varaiable. <a href="#fig-pvals-fig2i" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> is the plot of the modeled means, 95% confidence intervals of the mean, and <em>p</em>-value of the significance test of the effect of treatment on liver triacylglycerol.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pvals-fig2i" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pvals-fig2i-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="p-values_files/figure-html/fig-pvals-fig2i-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pvals-fig2i-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: UCP1 expression, relative to the mean level in the control group. Mean (circle) and 95% confidence interval (line) are shown. Unadjusted p-values are from linear model with sh-RNA treatment and LPS treatment fully crossed.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The coefficients of the model, and the standard error, 95% confidence interval, test-statistic, and <em>p</em>-value of each coefficient are shown in <a href="#tbl-pval-fig2i" class="quarto-xref">Table&nbsp;<span>6.1</span></a>. Recall from <a href="../intro.html" class="quarto-xref"><span>Chapter 1</span></a> that, with this model, the coefficient for the intercept term is the mean <code>liver_tg</code> for the control group, which is the estimate of the true mean for a mice with functional ASK1 protein. And the coefficient for the treatmentASK1Δadipo term is the difference in means between the knockout and control group, which is the estimate for the true effect of knocking out ASK1 in the adipose tissue. The <em>p</em>-value for the estimate of the effect is 0.012. How do we interpret this number?</p>
<div class="cell">
<div id="tbl-pval-fig2i" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pval-fig2i-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Coefficient table of fig2i_m1
</figcaption>
<div aria-describedby="tbl-pval-fig2i-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2.5 %</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">61.5</td>
<td style="text-align: right;">4.98</td>
<td style="text-align: right;">12.3</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">50.4</td>
<td style="text-align: right;">72.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">treatmentASK1Δadipo</td>
<td style="text-align: right;">-21.6</td>
<td style="text-align: right;">7.05</td>
<td style="text-align: right;">-3.1</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">-37.3</td>
<td style="text-align: right;">-5.9</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<section id="a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution"><span class="header-section-number">6.1</span> A <em>p</em>-value is the probability of sampling a value as or more extreme than the test statistic if sampling from a null distribution</h2>
<p>The test statistic in the table above is a <em>t</em>-value. For this specific model, this <em>t</em>-value is precisely the <em>t</em>-value one would get if they executed a classical Student <em>t</em>-test on the two groups of liver TG values. Importantly, this is not generally true. For many of the models in this text, a <em>t</em>-value is computed but this is <em>not</em> the <em>t</em>-value that would be computed in a classical <em>t</em>-test.</p>
<p>When we do a <em>t</em>-test, we get a <em>p</em>-value. The probability returned in a <em>t</em>-test is <span class="math inline">\(p = \mathrm{prob}(t \ge t_{obs} | H_0)\)</span>. Read this as “the p-value is the probability of observing a t-value that is greater than or equal to the observed t-value, given the null model is true.” Probability, in this text, is a long run frequency of sampling. The specific probability associated with the effect of treatment on liver TG is the long-run frequency of observing a <em>t</em>-value as big or bigger than the observed <em>t</em>-value (the one you actually got with your data) if the null is true. Let’s parse this into “long run frequency of observing a <em>t</em>-value as big or bigger than the observed <em>t</em>-value” and “null is true”.</p>
<p>A thought experiment: You open a google sheet and insert 12 standard, normal random deviates (so the true mean is zero and the true variance is one) in Column A, rows 1-12. You arbitrarily assign the first six values (rows 1-6) to treatment A and the second six values (rows 7-12) to treatment B. You use the space immediately below these data to compute the mean of treatment A, the mean of treatment B, the difference in means (A - B), and a <em>t</em>-value. Unfortunately, google sheets doesn’t have a <em>t</em>-value function so you’d have to compute this yourself. Or not, since this is a thought experiment. Now “fill right” or copy and paste these functions into 999 new columns. You now have 1000 <em>t</em>-tests. The expected value of the difference in means is zero (why?) but the actual values will form a normal distribution about zero. Most will be close to zero (either in the negative or positive direction) but some will be further from zero. The expected <em>t</em>-value will also be zero (why?) and the distribution of these 1000 <em>t</em>-values will look normal but the tails are a little fuller. This row of <em>t</em>-values is a null distribution, because in generating the data we used the exact same formula for the values assigned to A and the values assigned to B. Now think of a <em>t</em>-value in your head, say 0.72 (remember that <em>t</em>-values will largely range from about -3 to +3 although the theoretical range is <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span>. What is the probability of observing a <em>t</em> of 0.72 <em>or bigger</em> if the null is true? Look at the row of <em>t</em>-values! Count the number of <span class="math inline">\(t \ge 0.72\)</span> and then divide by the total number of <em>t</em>-values in the row (1000) and you have a probability computed as a frequency. But remember the frequentist definition is the long run frequency, or the expected frequency at the limit (when you’ve generated not 1000 or even 1,000,000 but an infinite number of columns and <em>t</em>-values).</p>
<p>Some asides to the thought experiment: First, why “as big or bigger” and not just the probability of the value itself? The reason is that the probability of finding the exact <em>t</em> is 1/infinity, which doesn’t do us much good. So instead we compute the probability of finding <em>t</em> as big, or bigger, than our observed <em>t</em>. Second, the <em>t</em>-test probability described above is a “one-tail probability”. Because a difference can be both in the positive direction and the negative direction, we usually want to count all the <span class="math inline">\(t \ge 0.72\)</span> and the <span class="math inline">\(t \le -0.72\)</span> and then add these two counts to compute the frequency of <em>as extreme or more extreme</em> values. This is called a “two-tailed probability” because we find extremes at both tails of the distribution. Third, we don’t really count <span class="math inline">\(t \ge 0.72\)</span> but take advantage of the beautiful mathematical properties of the theoretical <em>t</em> distribution, which allows us to compute the frequentist probability (expected long range frequency) given the <em>t</em>-value and the degrees of freedom using the <em>t</em>-distribution.</p>
<p>Now what do I mean with the phrase “null is true”? Most people equate “null is true” with “no difference in means” but the phrase entails much more than this. Effectively, the phrase is short for “all assumptions used to compute” the <em>p</em>-value (see the Sander Greenland quote at the start of this chapter). A <em>p</em>-value is based on modeling the real data with a theoretical sample in which all the values were randomly sampled from the same distribution and the assignment of the individual values to treatment was random. Random sampling from the same distribution has three important consequences. First, random assignment to treatment group means that the expected means of each group are the same, or put differently, the expected difference in means between the assigned groups is zero. Second, random assignment to treatment <em>also</em> means that the expected variances of the two groups are equal. And third, random sampling means that the values of each point are independent – we cannot predict the value of one point knowing information about any other point. <strong>Here is what is super important about this</strong>: a <em>p</em>-value is less reliable if <em>any</em> one of these consequences is untrue about our data. A low <em>p</em>-value could arise from a difference in true means, or it could arise from a difference in true variances, or it could arise if the <span class="math inline">\(Y\)</span> values are not independent of each other. This is why we need certain assumptions to make a <em>p</em>-value meaningful for empirical data. By assuming independent error and homogenous (equal) variances in our two samples, a low <em>p</em>-value is evidence of unequal means.</p>
<p>Let’s summarize: A pretty good definition of a <em>p</em>-value is: the long-run frequency of observing a test-statistic as large or larger than the observed statistic, if the null were true. A more succinct way to state this is</p>
<p><span class="math display">\[
p = \mathrm{prob}(t \ge t_o | H_o)
\]</span></p>
<p>where <em>t</em> is a hypothetically sampled <em>t</em>-value from a null distribution, <span class="math inline">\(t_o\)</span> is the observed <em>t</em>-value, and <span class="math inline">\(H_o\)</span> is the null hypothesis. Part of the null hypothesis is the expected value of the parameter estimated is usually (but not always) zero – this can be called the nil null. For example, if there is no ASK1 deletion effect on liver TG levels, then the expected difference between the means of the control and knockout mice is zero. Or,</p>
<p><span class="math display">\[
\mathrm{E}(\bar{Y}_{knockout} - \bar{Y}_{control} | H_o) = 0.0
\]</span></p>
</section>
<section id="pump-your-intuition-creating-a-null-distribution" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="pump-your-intuition-creating-a-null-distribution"><span class="header-section-number">6.2</span> Pump your intuition – Creating a null distribution</h2>
<p>The mean <code>liver_tg</code> in the knockout treatment is 21.6 µmol less than the mean <code>liver_tg</code> in the control treatment. This is the measured effect, or the <strong>observed differences in means</strong>. How confident are we in this effect? Certainly, if the researchers did the experiment comparing two control (ASK1F/F) groups, instead of a control and treatment group, they would measure some difference in their means simply because of sampling (that is which mice were sampled for the experiment). So let’s reframe the question: are the observed differences unusually large compared to a distribution of differences that would occur if there were no effect? That is, if the “null were true”. To answer this, we compare our observed difference to this <strong>null distribution</strong>. This comparison gives the probability (a long-run frequency) of “sampling” a random difference from the null distribution of differences that is as large, or larger, than the observed difference.</p>
<p>What is a null distribution? It is the distribution of a statistic (such as a difference in means, or better, a <em>t</em>-value) if the null were true. Here, I hope to pump your intuition by generating a null distribution that is relevant to the ASK1 liver TG data. See if you can understand the script before reading the explanation below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>seed <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>n_rep <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span> <span class="co"># number of replicate experiments</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(fig2i[treatment <span class="sc">==</span> <span class="st">"ASK1F/F"</span>, liver_tg]) </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">sd</span>(fig2i[treatment <span class="sc">==</span> <span class="st">"ASK1F/F"</span>, liver_tg])</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(fig2i[treatment <span class="sc">==</span> <span class="st">"ASK1F/F"</span>,])</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>d_null <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_rep)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(rep <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_rep){</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  sample_1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  sample_2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  d_null[rep] <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample_2) <span class="sc">-</span> <span class="fu">mean</span>(sample_1)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>d_data <span class="ot">&lt;-</span> <span class="fu">data.table</span>(</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"d_null"</span> <span class="ot">=</span> d_null</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> d_data,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> d_null)) <span class="sc">+</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> pal_okabe_ito[<span class="dv">1</span>],</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_pubr</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="p-values_files/figure-html/pvalue-d-null-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Null distribution for the difference in means of two samples from the same, inifinitely large population with a true mean and standard deviation equal to the observed mean and standard deviation of the ASK1 liver TG data.</figcaption>
</figure>
</div>
</div>
</div>
<p>What have we done above? using the <code>rnorm</code> function, we’ve simulated an infinitely large population of mice that have a distribution of liver TG values similar to that of the mice assigned to the control (ASK1F/F) group. The true mean (<span class="math inline">\(\mu\)</span>) and standard deviation (<span class="math inline">\(\sigma\)</span>) of the simulated TG level are equal to the observed mean and standard deviation of the TG levels of the control mice.</p>
<ol type="1">
<li>randomly sample 6 values from this population of simulated liver TG values and assign to <span class="math inline">\(\texttt{sample\_1}\)</span>. We sample 6 values because that is the sample size of our control in the experiment.</li>
<li>randomly sample 6 values from <strong>the same</strong> population of simulated liver TG values and assign to <span class="math inline">\(\texttt{sample\_2}\)</span>.</li>
<li>compute the difference of the means: <span class="math inline">\(\bar{Y}_{sample\_2} - \bar{Y}_{sample\_1}\)</span>.</li>
<li>repeat 1-3 100,000 times, each time saving the difference in means.</li>
<li>plot the distribution of the 100,000 differences using a histogram</li>
</ol>
<p>The distribution of the differences is a null distribution. Notice that the mode of the null distribution is at zero, and the mean (-0.0313) is close to zero (if we had set <span class="math inline">\(n\)</span> to infinity, the mean would be precisely zero). <em>The expected difference between the means of two random samples from the same population is, of course, zero</em>. Don’t gloss over this statement if that is not obvious. The tails extend out to a little more than +20 and -20. What this means is that it would be uncommon to randomly sample a value from this distribution of differences <em>as or more extreme</em> than our observed difference, -21.6. By “more extreme”, I mean any value more negative than -21.6 or more postive than 21.6. So it would be uncommon to sample a value from this distribution whose <em>absolute value</em> is as or more extreme than 21.6. How uncommon would this be?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>diff_obs <span class="ot">&lt;-</span> fig2i_m1_coef[<span class="st">"treatmentASK1Δadipo"</span>, <span class="st">"Estimate"</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>null_diff_extreme <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">abs</span>(d_null) <span class="sc">&gt;</span> <span class="fu">abs</span>(diff_obs))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>n_extreme <span class="ot">&lt;-</span> <span class="fu">length</span>(null_diff_extreme)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>(<span class="at">p_d_null =</span> n_extreme<span class="sc">/</span>n_rep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00529</code></pre>
</div>
</div>
<p>In the 100,000 runs, only 529 generated data with an absolute difference as large or larger than 21.6 (an “absolute difference” is the absolute value of the difference). The frequency of differences as large or larger than our observed difference is 0.00529. This frequency is the <em>probability</em> of sampling a difference as or more extreme than the observed difference “under the null”. It is a <em>p</em>-value, but it is not the <em>p</em>-value in the coefficient table. This is because the <em>p</em>-value in the coefficient table is computed from a distribution of <em>t</em>-values, not raw differences. This raises the question, what is a <em>t</em>-distribution, and a <em>t</em>-value, more generally?</p>
</section>
<section id="a-null-distribution-of-t-values-the-t-distribution" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="a-null-distribution-of-t-values-the-t-distribution"><span class="header-section-number">6.3</span> A null distribution of <em>t</em>-values – the <em>t</em> distribution</h2>
<p>A <em>t</em>-test is a test of differences between two values. These could be</p>
<ol type="1">
<li>the difference between the means of two samples (a “two-sample” <em>t</em>-test)</li>
<li>the difference between a mean of a sample and some pre-specified value (a “one-sample” <em>t</em>-test)</li>
<li>the difference between a coefficient from a linear model and zero</li>
</ol>
<p>A <em>t</em>-test compares an observed <em>t</em>-value to a <em>t</em>-distribution. The null distribution introduced above was a distribution of mean differences under the null. A distribution of mean differences under the null is very specific to the mean and standard deviation of the population modeled and the sample size of the experiment. This isn’t generally useful, since it will be unique to every study (at least it wasn’t generally useful prior to the time of fast computers. One could, and some statisticians do, compute <em>p</em>-values using the algorithm above). A <em>t</em>-distribution is a way of transforming a null distribution of mean differences, which is unique to the study, into a distribution that is a function of sample size only.</p>
<p>A <em>t</em>-distribution is a distribution of <em>t</em>-values under the null, where a <em>t</em>-value is a difference <em>standardized by its standard error</em>. For a two-sample <em>t</em>-test, this is</p>
<p><span id="eq-t"><span class="math display">\[
t = \frac{\bar{y}_2 - \bar{y}_1}{SE_{\bar{y}_2 - \bar{y}_1}}
\tag{6.1}\]</span></span></p>
<p>The numerator is <strong>the effect</strong> while the denominator is the precision of the estimate. Like many test statistics, a <em>t</em>-value is a signal-to-noise ratio – the effect is the signal and the SE of the difference is the noise.</p>
<p>A <em>t</em> distribution looks like a standard, normal distribution, except the tails are heavy, meaning there are more large-ish values than the normal. Like the standard normal distribution, large <em>t</em>-values are unlikely under the null and, therefore, a large <em>t</em> has a low probability – or <em>p</em>-value – under the null.</p>
<p>Looking at the equation for the two-sample <em>t</em>-test above, it is easy to see that three features of an experiment are associated with large <em>t</em> and small <em>p</em>-values: 1) big effect size (the numerator of the equation), 2) small sample standard deviations (which results in small standard errors of the difference, the denominator of <a href="#eq-t" class="quarto-xref">Equation&nbsp;<span>6.1</span></a>, and 3) large sample size (which results in small standard errors of the difference). As a quick-and-dirty generalization, absolute t-values greater than 3 are uncommon if the null is true.</p>
<p>The <em>p</em>-value for a <em>t</em>-test comes from comparing the observed <em>t</em> to a null <em>t</em> distribution and “counting” the values that are more extreme than the observed <em>t</em>. The <em>p</em>-value is the relative frequency of these more extreme values (relative to the total number of <em>t</em>-values in the distribution). I have “counting” in quotes because nothing is really counted – there are an infinite number of <em>t</em>-values in the <em>t</em>-distribution. Instead, the t-distribution function is integrated to compute the fraction of the total area under the curve with <em>t</em>-values more extreme than the observed value. In a <strong>two-tailed test</strong>, this fraction includes both tails (positive <em>t</em>-values more positive than <span class="math inline">\(|t|_{observed}\)</span> and negative <em>t</em>-values more negative than <span class="math inline">\(-|t|_{observed}\)</span>.</p>
<p>Let’s repeat the simulation of a null distribution of mean differences above but add the computation of the t-value for each replicate comparison in order to generate a null distribution of <em>t</em>-values. Importantly, I’ve also changed bits of the code to more properly think about what a computed <em>t</em>-value is. These changes are:</p>
<ol type="1">
<li>I want to think of the first sample as being assigned to “WT” and the second sample as being assigned to “KO”. But, the KO sample is drawn from the same distribution (the same hat of numbers) as the WT sample – this guarantees that there is no difference in expected mean.</li>
<li>I want to think of the observed variances of the WT and KO samples as sampled variances from this fake distribution. Therefore, I give the variance of the fake distribution the average of the observed WT and KO samples. The true (population) standard deviation (<span class="math inline">\(\sigma\)</span>) of the simulated data, then, is the square root of this averaged variance.</li>
</ol>
<p>I show the script, but don’t just cut and paste the code. Spend time thinking about what the each line does. Explore it by copying parts and pasting into console.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>out_path <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"output"</span>,<span class="st">"chap_pval-tnull.Rds"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>do_it <span class="ot">&lt;-</span> <span class="cn">FALSE</span> <span class="co"># set this to TRUE to run and save to output folder</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(do_it){</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  seed <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  n_rep <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span> <span class="co"># number of iterations</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(fig2i[treatment <span class="sc">==</span> <span class="st">"ASK1F/F"</span>, liver_tg])</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  sd_control <span class="ot">&lt;-</span> <span class="fu">sd</span>(fig2i[treatment <span class="sc">==</span> <span class="st">"ASK1F/F"</span>, liver_tg])</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  sd_knockout <span class="ot">&lt;-</span> <span class="fu">sd</span>(fig2i[treatment <span class="sc">==</span> <span class="st">"ASK1Δadipo"</span>, liver_tg])</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  sigma <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((sd_control<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> sd_knockout<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(fig2i[treatment <span class="sc">==</span> <span class="st">"ASK1F/F"</span>,])</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  treatment <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"WT"</span>, <span class="st">"KO"</span>), <span class="at">each =</span> n) <span class="sc">|&gt;</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">factor</span>(<span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"WT"</span>, <span class="st">"KO"</span>)) <span class="co"># need this for for-loop</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  t_null <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  t_null_manual <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(rep <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_rep){</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    wt_sample <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    ko_sample <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># way no.1 - compute the t-tests using the linear model</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    y <span class="ot">&lt;-</span> <span class="fu">c</span>(wt_sample, ko_sample)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> treatment)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    t_null[rep] <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m1))[<span class="st">"treatmentKO"</span>, <span class="st">"t value"</span>]</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># way no. 2 - compute the t-tests manually!</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># check to make sure these are the same as t_null !!!</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    diff <span class="ot">&lt;-</span> <span class="fu">mean</span>(ko_sample) <span class="sc">-</span> <span class="fu">mean</span>(wt_sample)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>    se_diff <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">sd</span>(ko_sample)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n <span class="sc">+</span> <span class="fu">sd</span>(wt_sample)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    t_null_manual[rep] <span class="ot">&lt;-</span> diff<span class="sc">/</span>se_diff</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">saveRDS</span>(t_null, out_path)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>t_null <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(out_path)</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>t_data <span class="ot">&lt;-</span> <span class="fu">data.table</span>(</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>  <span class="st">"t_null"</span> <span class="ot">=</span> t_null</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> t_data,</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> t_null)) <span class="sc">+</span></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> pal_okabe_ito[<span class="dv">1</span>],</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_pubr</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="p-values_files/figure-html/pvalue-t-null-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Null distribution of t-values. The simulation generated 10,000 t-tests with a true null.</figcaption>
</figure>
</div>
</div>
</div>
<p>Now let’s use this null distribution of <em>t</em>-values to compute a <em>p</em>-value</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># what is the p-value?</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the p-value is the number of t-values in t_null_2 that are as large</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># or larger than the observed t. Large, negative t-values</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># are as unlikely under the null as large, positive t-values.</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># To account for this, we want to use absolute values in our counts</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># this is a "two-tail test"</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># first assign the observed t-value</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>t_obs <span class="ot">&lt;-</span> fig2i_m1_coef[<span class="st">"treatmentASK1Δadipo"</span>, <span class="st">"t value"</span>]</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># now count the number of t-values in t_dis as big or bigger than this</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># include the observed value as one of these (so add 1 to the count)</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>count <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">abs</span>(t_null) <span class="sc">&gt;=</span> <span class="fu">abs</span>(t_obs))</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co"># the p-value is the frequency of t_dis &gt;= t_obs, so divide</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="co"># count by the total number of t-values in the distribution.</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Again add one since the observed value counts as a sample</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>(p_ASK1 <span class="ot">&lt;-</span> count<span class="sc">/</span>(n_rep))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01146</code></pre>
</div>
</div>
<p>Hey that looks pretty good! Compare this to the <em>p</em>-value in the coefficient table above.</p>
<p>A <em>p</em>-value can be computed by counting the number of simulated <em>t</em>-values, <em>including the observed value</em>, that are equal to or more extreme (in either the positive or negative direction) than the observed <em>t</em>. Including the observed <em>t</em>, there are 1146 values that are more extreme than that observed. An approximate measure of <em>p</em> is this count divided by 100,001 (why is 1 added to the denominator?), which is 0.01146. This simulation-based <em>p</em>-value is very (very!) close to that computed from the observed <em>t</em>-test.</p>
</section>
<section id="p-values-from-the-perspective-of-permutation" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="p-values-from-the-perspective-of-permutation"><span class="header-section-number">6.4</span> P-values from the perspective of permutation</h2>
<p>A very intuitive way to think about <em>p</em>-values as a frequency is <strong>random permutation</strong>. A permutation is a re-arrangement of items. If there is an effect of ASK1 deletion on liver TG, then the arrangement of the values in the <code>treatment</code> column matters. If there is no effect of ASK1 deletion on liver TG, then the arrangement of the values in the <code>treatment</code> column does not matter.</p>
<p>Think about the structure of the liver TG data: there are two columns, <code>treatment</code>, which contains the assigned treatment, and <code>liver_tg</code>. The values in the <code>treatment</code> column were randomly assigned prior to the start of the experiment. If there is a negative effect of ASK1 deletion on liver TG, then assginment matters – the values in the <code>liver_tg</code> column for the ASK1Δadipo rows will be smaller than, on average, the values in the ASK1F/F rows. That is, a specific value of a<code>liver_tg</code> is what it is because of the value of <code>treatement</code> in the same row. Assignment to ASK1F/F or ASK1Δadipo changes the expected value of <code>liver_tg</code>. But, if there were no true effect, then assignment to ASK1F/F or ASK1Δadipo does not change the expected value of <code>liver_tg</code>. The expected value of every cell in the <code>liver_tg</code> column would be the same regardless of what is in the <code>treatment</code> column.</p>
<p>In our thought experiment, let’s leave the values in the <code>treatment</code> column be, and just randomly re-arrange or permute the values in the <code>liver_tg</code> column. What is the new expected diference in liver TG between the rows assigned to ASK1F/F and the rows assigned to ASK1Δadipo? The expected difference is Zero. Because the <code>liver_tg</code> values were randomly re-arranged, they <em>cannot</em> be caused by treatment assignment.</p>
<p>A permutation is a random re-arrangement of values in a column. Consider the many thousands of permutations of the values in the <code>liver_tg</code> column. A difference in means can be computed from each of these permuations and a distribution of differences can be generated. Is the observed difference extreme relative to the other values in this distribution? This is a permutation test – it compares an observed statistic to a distribution of the statistic computed over many thousands of permutations.</p>
<p>Let’s create a script for a permutation test</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>n_iter <span class="ot">&lt;-</span> <span class="dv">5000</span> <span class="co"># number of random permutations</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> fig2i[, liver_tg]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> fig2i[, treatment]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>perm_diff <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_iter) <span class="co"># this is a vector to hold the difference in means each iteration</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(iter <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_iter){</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  xbar1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y[x <span class="sc">==</span> <span class="st">"ASK1F/F"</span>])</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  xbar2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y[x <span class="sc">==</span> <span class="st">"ASK1Δadipo"</span>])</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  perm_diff[iter] <span class="ot">&lt;-</span> xbar2 <span class="sc">-</span> xbar1</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># permute y</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">sample</span>(y, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># note that, when i=1, the first "permutation" is the original arrangement</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>diff_data <span class="ot">&lt;-</span> <span class="fu">data.table</span>(</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">Difference =</span> perm_diff</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> diff_data,</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Difference)) <span class="sc">+</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> pal_okabe_ito[<span class="dv">1</span>],</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_pubr</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="p-values_files/figure-html/pvalue-d-dist-perm-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this distribution of distances generated by random permuation of the response, we can compute a permutation <em>p</em>-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(p_permute <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">abs</span>(perm_diff) <span class="sc">&gt;=</span> <span class="fu">abs</span>(perm_diff[<span class="dv">1</span>]))<span class="sc">/</span>n_iter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0076</code></pre>
</div>
</div>
</section>
<section id="parametric-vs.-non-parametric-statistics" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="parametric-vs.-non-parametric-statistics"><span class="header-section-number">6.5</span> Parametric vs.&nbsp;non-parametric statistics</h2>
<p>A statistic such as the difference in mean liver TG between ASK1Δadipo and ASK1F/F groups does not have “a” <em>p</em>-value. A <em>p</em>-value is the probability of observing an event <em>given a model of how the event was generated</em>. For the <em>p</em>-value in the coefficient table above, the event is sampling a <em>t</em>-value from a modeled <em>t</em> distribution that is as or more extreme than the observed <em>t</em>-value. The model generating the null distribution of <em>t</em>-values includes random sampling from a distribution that is defined by specific parameters (in this case, a mean and a variance), these parameters define the location and shape of the distribution of values that could be sampled. A <em>p</em>-value computed from a distribution that is defined by a set of parameters is a <strong>parametric</strong> <em>p</em>-value.</p>
<p>For the <em>p</em>-value computed using the permutation test, the event is the probability of of computing a difference of means <em>from a randomly permuted set of <span class="math inline">\(Y\)</span></em> as or more extreme than the observed difference of means. The distribution of differences from the permutated <span class="math inline">\(Y\)</span> data sets was not generated by any of the known distributions (normal, Poisson, binomial, etc.) given a specific value of parameters. Consequently, the permutation <em>p</em>-value is <strong>non-parametric</strong>.</p>
<p>The validity of all <em>p</em>-values depends on a set of model assumptions, which differ from model to model. The permutation <em>p</em>-value has fewer assumptions than a parametric <em>p</em>-value because no distribution is assumed (the permutation <em>p</em>-value is <strong>distribution-free</strong>).</p>
</section>
<section id="frequentist-probability-and-the-interpretation-of-p-values" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="frequentist-probability-and-the-interpretation-of-p-values"><span class="header-section-number">6.6</span> frequentist probability and the interpretation of p-values</h2>
<section id="background" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="background"><span class="header-section-number">6.6.1</span> Background</h3>
<p>There are at least three different meanings of <strong>probability</strong>.</p>
<ol type="1">
<li><p><strong>subjective probability</strong> is the probability that an individual assigns to an event based on prior knowledge and the kinds of information considered reliable evidence. For example, if I asked a sample of students, what is the probability that a 30c homeopathic medicine could clear a <em>Streptococcus</em> infection from your respiratory system, their answers would differ because of variation in their knowledge of basic science, including chemistry and physics, their knowledge of what homeopathic medicines are, and how they weight different kinds of evidence.</p></li>
<li><p><strong>classical probability</strong> is simply one divided by the number of possible unique events. For example, with a six-sided die, there are six possible unique events. The probability of rolling a 2 is <span class="math inline">\(\frac{1}{6}\)</span> and the probability of rolling an odd number is <span class="math inline">\(\frac{1}{2}\)</span>.</p></li>
<li><p><strong>frequentist probability</strong> is based on the concept of <strong>long run frequency</strong>. If I roll a die 10 times, the frequency of rolling a 2 will be approximately <span class="math inline">\(\frac{1}{6}\)</span>. If I roll the die 100 times, the frequency of rolling a two will be closer to <span class="math inline">\(\frac{1}{6}\)</span>. If I roll the die 1000 times, the frequency of rolling the die will be even closer to <span class="math inline">\(\frac{1}{6}\)</span>. So the frequentist definition is the expected frequency given an infinite number of rolls. For events with continous outcomes, a frequentist probability is the long run frquency of <em>observing an outcome equal to or more extreme that that observed</em>.</p></li>
</ol>
</section>
<section id="this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability." class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability."><span class="header-section-number">6.6.2</span> This book covers frequentist approaches to statistical modeling and when a probability arises, such as the <em>p</em>-value of a test statistic, this will be a frequentist probability.</h3>
<p>When we do a <em>t</em>-test, we get a <em>p</em>-value. There are several ways to think about this probability. The most compact way is <span class="math inline">\(P(data | null)\)</span>, which is literally read as the probability of the data given the null (or “conditional” on the null), but is really short for <em>the probability of the data, or something more extreme than the data, given that the null hypothesis is true</em>. The “probability of the data” is kinda vague. More specifically, we mean the probability of some statistic about the data such as the difference in means between group A and group B or the <em>t</em>-value associated with this difference. So, a bit more formally, the probability returned in a <em>t</em>-test is <span class="math inline">\(\mathrm{prob}(t \ge t_{obs} | H_0)\)</span>. This is the long run frequency of observing a <em>t</em>-value as big or bigger than the observed <em>t</em>-value (the one you actually got with your data) if the null is true. Let’s parse this into “long run frequency of observing a <em>t</em>-value as big or bigger than the observed <em>t</em>-value” and “null is true”.</p>
<p>A thought experiment: You open a google sheet and insert 12 standard, normal random deviates (so the true mean is zero and the true variance is one) in Column A, rows 1-12. You arbitrarily assign the first six values (rows 1-6) to treatment A and the second six values (rows 7-12) to treatment B. You use the space immediately below these data to compute the mean of treatment A, the mean of treatment B, the difference in means (A - B), and a <em>t</em>-value. Unfortunately, google sheets doesn’t have a <em>t</em>-value function so you’d have to compute this yourself. Or not, since this is a thought experiment. Now ``fill right’’ or copy and paste these functions into 999 new columns. You now have 1000 <em>t</em> tests. The expected value of the difference in means is zero (why?) but the actual values will form a normal distribution about zero. Most will be close to zero (either in the negative or positive direction) but some will be further from zero. The expected <em>t</em>-value will also be zero (why?) and the distribution of these 1000 <em>t</em>-values will look normal but the tails are a little fuller. This row of <em>t</em>-values is a null distribution, because in generating the data we used the exact same formula for the values assigned to A and the values assigned to B. Now think of a <em>t</em>-value in your head, say 0.72 (remember that <em>t</em>-values will largely range from about -3 to +3 although the theoretical range is <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span>. What is the probability of observing a <em>t</em> of 0.72 <em>or bigger</em> if the null is true? Look at the row of <em>t</em>-values! Count the number of <span class="math inline">\(t \ge 0.72\)</span> and then divide by the total number of <em>t</em>-values in the row (1000) and you have a probability computed as a frequency. But remember the frequentist definition is the long run frequency, or the expected frequency at the limit (when you’ve generated not 1000 or even 1,000,000 but an infinite number of columns and <em>t</em>-values).</p>
<p>Some asides to the thought experiment: First, why “as big or bigger” and not just the probability of the value itself? The reason is that the probability of finding the exact <em>t</em> is 1/infinity, which doesn’t do us much good. So instead we compute the probability of finding <em>t</em> as big, or bigger, than our observed <em>t</em>. Second, the <em>t</em>-test probability described above is a “one-tail probability”. Because a difference can be both in the positive direction and the negative direction, we usually want to count all the <span class="math inline">\(t \ge 0.72\)</span> and the <span class="math inline">\(t \le -0.72\)</span> and then add these two counts to compute the frequency of <em>as extreme or more extreme</em> values. This is called a “two-tailed probability” because we find extremes at both tails of the distribution. Third, we don’t really count <span class="math inline">\(t \ge 0.72\)</span> but take advantage of the beautiful mathematical properties of the theoretical <em>t</em> distribution, which allows us to compute the frequentist probability (expected long range frequency) given the <em>t</em>-value and the degrees of freedom using the <em>t</em>-distribution.</p>
<p>Now what do I mean with the phrase “null is true”? Most people equate “null is true” with ``no difference in means’’ but the phrase entails much more than this. Effectively, the phrase means that the <em>p</em>-value is based on modeling the real data with a theoretical sample in which all the points were randomly sampled from the same distribution and that the assignment of the individual points to treatment was random. This model means the theoretical sample has three properties: First, random assignment to treatment after sampling from the same distribution means that the expected means are the same, or put differently, the expected difference in means between the assigned groups is zero. Second, random assignment to treatment after sampling from the same distribution <em>also</em> means that the expected variances of the two groups are equal. And third, random sampling means that the values of each point are independent – we cannot predict the value of one point knowing information about any other point. <strong>Here is what is super important about this</strong>: if we get a really low <em>p</em>-value, any one of these consequences may be untrue about our data, for example it could be that the true means of the two treatment groups really are different, or it could mean it is the variances that differ between the two groups, or it could mean that the data (or technically, the errors) are not independent of each other. This is why we need certain assumptions to make a <em>p</em>-value meaningful for empirical data. By assuming independent error and homogenous (equal) variances in our two samples, a low <em>p</em>-value is evidence of unequal means.</p>
</section>
<section id="two-interpretations-of-the-p-value" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="two-interpretations-of-the-p-value"><span class="header-section-number">6.6.3</span> Two interpretations of the <em>p</em>-value</h3>
<p>Since we want to be working scientists who want to use <em>p</em>-values as a tool, we need to know how to interpret (or use) the <em>p</em>-value to make reasonable inferences and how to avoid mis-interpreting the <em>p</em>-value and making unreasonable or even incorrect inferences. Two different interpretations of the <em>p</em>-value arose during the development of frequentist statistics. Ronald Fisher (who developed the bulk of the framework of frequentist statistics) thought of the <em>p</em>-value as a quantitative measure of evidence against the null hypothesis. Jerzy Neyman and Egon Pearson (Neyman-Pearson) thought of the <em>p</em>-value as a qualitative, threshold metric used for decision making – to act as if there is an effect. Modern researchers in biology typically use an interpretation that is an odd hybrid of the two, which often leads to illogical inference. Regardless, understanding the distinction between Fisher and Neyman-Pearson will inform how we write up our results in a manuscript.</p>
<p>Fisher was working in the context of an agricultural experiments, the goal of which was to discover better agricultural practices – how do the yields in these five varieties of crop differ under this agricultural practice? Fisher thought of <em>p</em> as evidence against the null; the smaller the <em>p</em>, the stronger the evidence that the mean of the two sampling distributions differ <em>given all model assumptions are true</em>. Fisher never thought of a single experiment as definitive. Any decision following an experiment is only partly informed by the <em>p</em>-value and Fisher offered no formal rule about what <em>p</em>-value lies on the threshold of this decision.</p>
<p>Neyman-Pearson thought of <em>p</em> as the necessary and sufficient information <em>to make a decision</em> between accepting the null (or at least not rejecting the null) or rejecting the null and accepting an alternative hypothesis. This decision balances two sorts of errors: Type I (false positives), which they called <span class="math inline">\(\alpha\)</span>, and Type II (false negatives), which they called <span class="math inline">\(\beta\)</span>. A false positive occurs when the null is rejected (because <span class="math inline">\(p &lt; \alpha\)</span>) but there is no effect of treatment (the null is true). A false negative occurs when the test fails to reject the null (because <span class="math inline">\(p &gt; \alpha\)</span>) but there actually is an effect (the null is false). <span class="math inline">\(\alpha\)</span> is set by the experimenter and is the long-term frequency (or “rate”) of false positives <strong>when the null is true</strong> that the experimenters are willing to accept.</p>
<p>After setting <span class="math inline">\(\alpha\)</span>, the experimenter designs the experiment to achieve an acceptable rate of <span class="math inline">\(\beta\)</span>. Since <span class="math inline">\(\beta\)</span> is the false negative rate, <span class="math inline">\(1-\beta\)</span> is the rate of <em>not</em> making a false negative error. Or, stated without the double negative, <span class="math inline">\(1-\beta\)</span> is the rate of rejecting the null (“finding an effect”) when there really is an effect. This is called the <strong>power</strong> of the experiment. An experiment with high power will have a low probability of a Type II error. An experiment with low power will have a high probability of a Type II error. Power is partly determined by sample size, the bigger the sample the smaller the <em>p</em>-value, all other things equal (think about why in the context of the formula for the <em>t</em>-value). Power is a function of error variance, both the natural variance and the component added because of measurement error (think about why in the context of the formula for the <em>t</em>-value). Power is also a function of <span class="math inline">\(\alpha\)</span>. If we set a low <span class="math inline">\(\alpha\)</span> (say, <span class="math inline">\(\alpha=0.01\)</span>), the test is conservative. We are more likely to fail to reject the null even if the null is false. A researcher can increase power by increasing sample size, using clever strategies to reduce measurement error, or increasing alpha.</p>
<p>An experimenter sets <span class="math inline">\(\alpha\)</span>, computes the sample size needed to achieve a certain level of power (<span class="math inline">\(1-\beta\)</span>), and then does the experiment. A thoughtful researcher will set <span class="math inline">\(\alpha\)</span> after considering and weighing the pros and cons of different levels of <span class="math inline">\(\alpha\)</span>. If false positives have costly consequences (expense, time, deleterious side-effects), then set <span class="math inline">\(\alpha\)</span> to a low value, such as 0.01 or 0.001. For example, if an initial screen has identified a previously unknown candidate that potentially functions in the focal system of the researcher, then a researcher might decide to set a low <span class="math inline">\(\alpha\)</span> (0.001) in the initial tests of this candidate to avoid devoting time, personnel, and expense to chasing a phantom (a false-positive candidate). If false positives have trivial consequences, then set <span class="math inline">\(\alpha\)</span> to a high value, such as 0.05, or 0.1, or even 0.2. For example, if the initial tests of a candidate in a functional system are cheap and fast to construct, then a researcher might choose to set a high <span class="math inline">\(\alpha\)</span> for the screen that identifies candidates. False positive candidates don’t cost the lab much effort to identify them as false, but missing positive candidates because of a small <span class="math inline">\(\alpha\)</span> (which results in low power) at the screen stage costs the researcher the discovery of a potentially exciting component of the functional system.</p>
<p>In Fisher’s interpretation, there is no <span class="math inline">\(\alpha\)</span>, no <span class="math inline">\(\beta\)</span>, no alternative hypothesis, and no sharp decision rule. Instead, in Fisher, <em>p</em> is a continuous measure of evidence against the null and its value is interpreted subjectively by an informed and knowledgeable expert using additional information to make decisions. Neyman-Pearson rejected Fisher’s conception of <em>p</em> as evidence against the null arguing that a single experimental <em>p</em>-value is too noisy without embedding it into a more formal system of of decision making that maintains long-term type I error rates at <span class="math inline">\(\alpha\)</span>, given a certain power. In Neyman-Pearson, <em>p</em> is compared to a threshold, <span class="math inline">\(\alpha\)</span> and this alone makes the decision. In Neyman-Pearson, <em>p</em> <strong>is not treated as continuous information</strong>. <span class="math inline">\(p=0.00000001\)</span> is no more evidence to use to reject the null than <span class="math inline">\(p=0.049\)</span>.</p>
</section>
<section id="nhst" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="nhst"><span class="header-section-number">6.6.4</span> NHST</h3>
<p>Most biology researchers today interpret <em>p</em> using a combination of Fisher and Neyman-Pearson concepts in what has become known as Null Hypothesis Significance Testing (NHST).</p>
<ol type="1">
<li>Nearly all papers in biology either explicitly state something like “P values &lt; 0.05 were considered to be statistically significant” or implicitly use 0.05 as the “level of significance” (<span class="math inline">\(\alpha\)</span>). Comparing a <em>p</em>-value to a pre-defined <span class="math inline">\(\alpha\)</span> is Neyman-Pearson.</li>
<li>Unlike Neyman-Pearson, there is little evidence that researchers are thoughtfully considering the level of <span class="math inline">\(\alpha\)</span> for each experiment. Instead, researchers mindlessly choose <span class="math inline">\(\alpha=0.05\)</span> because this is what everyone else uses.</li>
<li>Unlike Neyman-Pearson, but somewhat in the spirit of Fisher, researchers, journals, and textbooks, advocate polychotomizing a statistically significant <em>p</em> into “significance bins” – three asterisks for <span class="math inline">\(p &lt; 0.001\)</span>, two asterisks for <span class="math inline">\(0.001 &lt; p &lt; 0.01\)</span>, and one asterisk for <span class="math inline">\(0.01 &lt; p &lt; 0.05\)</span>). This is not Neyman-Pearson. Again, Neyman-Pearson developed a system to control the long-run frequency of Type I error, which is controlled by a strict use of <span class="math inline">\(\alpha\)</span>. If an observed <em>p</em>-value is in the *** bin or the * bin is meaningless in a system using Neyman-Pearson. There is only “accept” (<span class="math inline">\(p \ge \alpha\)</span>) or “reject” (<span class="math inline">\(p &lt; \alpha\)</span>).</li>
<li>Many researchers report exact <em>p</em>-values when <span class="math inline">\(p &lt; 0.05\)</span> but “n.s.” (not significant) when <span class="math inline">\(p &gt; 0.05\)</span>. Reporting exact <em>p</em>-values is Fisher. Reporting n.s. is Neyman-Pearson.</li>
<li>Many researchers further polychomotomize the <em>p</em>-value space just above 0.05 by using language such as “marginally significant”.</li>
</ol>
</section>
</section>
<section id="some-major-misconceptions-of-the-p-value" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="some-major-misconceptions-of-the-p-value"><span class="header-section-number">6.7</span> Some major misconceptions of the <em>p</em>-value</h2>
<p>Setting the type I error rate <span class="math inline">\(\alpha\)</span> to 0.05 is so pervasive that I’m going to simply use “0.05” instead of “alpha” in discussing misconceptions.</p>
<section id="misconception-p-0.05-means-there-is-no-effect-of-treatment" class="level3" data-number="6.7.1">
<h3 data-number="6.7.1" class="anchored" data-anchor-id="misconception-p-0.05-means-there-is-no-effect-of-treatment"><span class="header-section-number">6.7.1</span> Misconception: <span class="math inline">\(p &gt; 0.05\)</span> means there is no effect of treatment</h3>
<p>Many researchers believe that if <span class="math inline">\(p &gt; 0.05\)</span> then “there is no effect.” A frequentist hypothesis test cannot show that an effect doesn’t exist, only that the null has a low probablity of producing a test statistic as extreme or more extreme than the observed effect. Even if there is a true effect of treatment, a high <em>p</em>-value can occur because of</p>
<ol type="1">
<li>a low signal:noise ratio, where the signal is the true effect size (the magnitude of the true difference in response) and the noise is the combination of intrinsic (biological) and extrinsic (experimental) error.</li>
<li>a small sample size, where small is relative to the sample size necessary for high power.</li>
</ol>
<p>The statement “There is no effect of knockout on glucose tolerance” is not a valid conclusion of a frequentist hypothesis test. The similar statement “We found no effect of knockout on glucose tolerance” is misleading because a frequentist hypothesis test can neither find an effect nor find no effect.</p>
</section>
<section id="misconception-a-p-value-is-repeatable" class="level3" data-number="6.7.2">
<h3 data-number="6.7.2" class="anchored" data-anchor-id="misconception-a-p-value-is-repeatable"><span class="header-section-number">6.7.2</span> Misconception: a <em>p</em>-value is repeatable</h3>
<p>Many researchers believe that a <em>p</em>-value is a precise measure – that if the experiment were replicated, a similar <em>p</em> would result. This belief requires at least two misconceptions. First, if the null were true, then <em>any</em> <em>p</em>-value is equally likely. <span class="math inline">\(p=0.00137\)</span> is just as likely as <span class="math inline">\(p=0.492\)</span>. In other words, if the null were true, the <em>p</em>-value is not replicable at all! Second, the <em>p</em>-value is highly dependent on the sample, and can be highly variable among replications, but there is no true <em>p</em>-value, so there can be no estimate or standard error. Let’s explore these.</p>
<section id="the-incredible-inconsistency-of-the-p-value" class="level4" data-number="6.7.2.1">
<h4 data-number="6.7.2.1" class="anchored" data-anchor-id="the-incredible-inconsistency-of-the-p-value"><span class="header-section-number">6.7.2.1</span> The incredible inconsistency of the <em>p</em>-value</h4>
<p>How replicable is the conclusion of an experiment if the <em>p</em>-value for a <em>t</em>-test is 0.03? If our conclusion is based on <span class="math inline">\(p &lt; 0.05\)</span>, then the conclusion is not very replicable. The simulation below shows the results of 15 replicates of an experiment with true power of 40%. There are five “significant” results (one less than expected) but several replicates have very high <em>p</em>-values.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="p-values_files/figure-html/dance-fig-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Variability of <em>p</em>-values when the power is 0.4</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="what-is-the-distribution-of-p-values-under-the-null" class="level4" data-number="6.7.2.2">
<h4 data-number="6.7.2.2" class="anchored" data-anchor-id="what-is-the-distribution-of-p-values-under-the-null"><span class="header-section-number">6.7.2.2</span> What is the distribution of <em>p</em>-values under the null?</h4>
<p>I often ask students, “if there is no true effect (no difference in means), and we were to repeat an experiment thousands of times, what is the most likely <em>p</em>-value?”. A common answer (although answers are uncommon) is <span class="math inline">\(p = 0.5\)</span>. Sometimes I rephrase the question, if there is no true effect (no difference in means), and we were to repeat an experiment thousands of times, what do you think the distribution of <em>p</em>-values would look like?” The typical answer to this is a the distribtion will look like a normal curve with the peak at 0.5, (presumably the tails abruptly stop at 0 and 1).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="p-values_files/figure-html/uniform-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="misconception-0.05-is-the-lifetime-rate-of-false-discoveries" class="level3" data-number="6.7.3">
<h3 data-number="6.7.3" class="anchored" data-anchor-id="misconception-0.05-is-the-lifetime-rate-of-false-discoveries"><span class="header-section-number">6.7.3</span> Misconception: 0.05 is the lifetime rate of false discoveries</h3>
<p>An important and widespread misconception is that if a researcher consistently uses <span class="math inline">\(\alpha=0.05\)</span>, then the frequency of incorrectly concluding an effect exists, or “discovering” an effect, over the lifetime of the researcher, will be 5%. This is incorrect. <span class="math inline">\(\alpha\)</span> is the rate of false positives <em>in the subset of tests in which the null hypothesis is true</em>. <span class="math inline">\(\alpha\)</span> is the Type I error rate.</p>
<p>Our mental conception of “lifetime rate of false discoveries” is the <strong>False Discovery Rate</strong>, and is the frequency of false positives divided by the frequency of positives (the sum of false and true positives).</p>
<p>To pump or intution about the differences between the Type I error rate and the False Discovery Rate, imagine we test</p>
<ol type="1">
<li>1000 null hypotheses over a lifetime</li>
<li>60% are true nulls, this means there are 600 true nulls and 400 true effects</li>
<li>alpha is 5%. This means we expect to find <span class="math inline">\(p \le 0.05\)</span> 30 times (<span class="math inline">\(0.05 \times 600\)</span>) when the null is true</li>
<li>power is 25%. This means we expect to find <span class="math inline">\(p \le 0.05\)</span> 100 times (<span class="math inline">\(0.25 \times 400\)</span>) when the null is false</li>
<li>We have made <span class="math inline">\(30 + 100=130\)</span> “discoveries” (all experiments with <span class="math inline">\(p \le 0.05\)</span>), but</li>
<li>30 of the 130, or 23%, are “false discoveries”. This is the false discovery rate.</li>
</ol>
<p>Think about this. If the null is never true, you cannot have a false discovery – every <span class="math inline">\(p \le 0.05\)</span> is a true discovery (the false discovery rate is 0%). And if the null is always true, every <span class="math inline">\(p &lt; 0.05\)</span> is a false discovery (the false discovery rate is 100%).</p>
</section>
<section id="misconception-a-low-p-value-indicates-an-important-effect" class="level3" data-number="6.7.4">
<h3 data-number="6.7.4" class="anchored" data-anchor-id="misconception-a-low-p-value-indicates-an-important-effect"><span class="header-section-number">6.7.4</span> Misconception: a low <em>p</em>-value indicates an important effect</h3>
<p>Many researchers write results as if they believe that a small <em>p</em>-value means the effect is big or important. This may misconception may arise because of the ubiquitous use of “significant” to indicate a small p-value and “very” or “extremely” or “wicked” significant to indicate a really small p-value. Regardless, this is a misconception. A small p-value will usually result when there is high power (but can occur even if power is low) and power is a function of effect size, variability (the standard deviation), and sample size. A small <em>p</em> could result from a large effect size but can also result with a small effect size if the sample size is big enough.</p>
<p>This is easy to simulate (see script below). Let’s model the effect of the genotype of a gene on height</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">4</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>genotype <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"+/+"</span>, <span class="st">"+/-"</span>, <span class="st">"-/-"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>Sigma <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="dv">2</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>Sigma[<span class="dv">1</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> Sigma[<span class="dv">2</span>,<span class="dv">1</span>] <span class="ot">&lt;-</span> rho</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rmvnorm</span>(n, <span class="at">mean=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">sigma=</span>Sigma)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(X) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"X1"</span>, <span class="st">"X2"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.05</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> X<span class="sc">%*%</span>beta <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(<span class="fu">summary</span>(fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 0.007472959 0.01007946 0.7414046 4.584656e-01
XX1         0.044304824 0.01154709 3.8368830 1.253725e-04
XX2         0.048228101 0.01170855 4.1190490 3.835033e-05</code></pre>
</div>
</div>
</section>
<section id="misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity" class="level3" data-number="6.7.5">
<h3 data-number="6.7.5" class="anchored" data-anchor-id="misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity"><span class="header-section-number">6.7.5</span> Misconception: a low <em>p</em>-value indicates high model fit or high predictive capacity</h3>
<p>On page 606, of Lock et al “Statistics: Unlocking the Power of Data”, the authors state in item D “The p-value from the ANOVA table is 0.000 so the model as a whole is effective at predicting grade point averages.” This is incorrect. A p-value is not a measure of the predictive capability of a model because the p-value is a function of the signal, noise (unmodeled error), and <em>sample size</em> while predictive ability is a function of just the signal:noise ratio. If the signal:noise ratio is tiny, the predictive ability is small but the p-value can be tiny if the sample size is large. This is easy to simulate (see script below). The whole-model p-value is exceptionally small (0.00001002) but the relative predictive ability, measured by the <span class="math inline">\(R^2\)</span>, is near zero (0.002).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">4</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>Sigma <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="dv">2</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>Sigma[<span class="dv">1</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> Sigma[<span class="dv">2</span>,<span class="dv">1</span>] <span class="ot">&lt;-</span> rho</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rmvnorm</span>(n, <span class="at">mean=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">sigma=</span>Sigma)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(X) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"X1"</span>, <span class="st">"X2"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="sc">-</span><span class="fl">0.05</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> X<span class="sc">%*%</span>beta <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.6449 -0.6857  0.0148  0.6756  3.6510 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.007473   0.010079   0.741 0.458466    
XX1          0.044305   0.011547   3.837 0.000125 ***
XX2         -0.051772   0.011709  -4.422  9.9e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.008 on 9997 degrees of freedom
Multiple R-squared:  0.0023,    Adjusted R-squared:  0.002101 
F-statistic: 11.52 on 2 and 9997 DF,  p-value: 1.002e-05</code></pre>
</div>
</div>
</section>
</section>
<section id="what-the-p-value-does-not-mean" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="what-the-p-value-does-not-mean"><span class="header-section-number">6.8</span> What the <em>p</em>-value does not mean</h2>
<ol type="1">
<li><em>p</em> is not the probability of the null being true. More formally, this probability is <span class="math inline">\(Prob(null | data)\)</span> but our <em>p</em>-value is <span class="math inline">\(P(data | null)\)</span>. These are not the same. <span class="math inline">\(P(null | data)\)</span> is the probability of the null being true given the data. <span class="math inline">\(P(data | null)\)</span> is the probability of our data, or something more extreme than our data, conditional on a true null.</li>
<li><span class="math inline">\(1-p\)</span> is not the probability of the alternative</li>
<li><em>p</em> is not a measure of effect size.</li>
<li><em>p</em> in one experiment is not the same level of evidence against the null as in another experiment</li>
<li><em>p</em> is not a great indicator of which is more likely, H0 or H1.</li>
<li>If one treatment level has <span class="math inline">\(p &lt; 0.05\)</span> and another treatment level has <span class="math inline">\(p &gt; 0.05\)</span>, this is not evidence that the treatment levels have different effects on the outcome.</li>
</ol>
</section>
<section id="on-using-p-values-in-experimental-biology" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="on-using-p-values-in-experimental-biology"><span class="header-section-number">6.9</span> On using <em>p</em>-values in experimental biology</h2>
<p>The flow of experiments in the article <a href="https://www.nature.com/articles/s41586-019-1911-y" target="_blank">GDF15 mediates the effects of metformin on body weight and energy balance</a> is typical of that in many experimental biology studies.</p>
<ol type="1">
<li>(Figure 1) A cited observational studying showing an association between metformin and increased blood levels of the peptide hormone GDF15 in humans led to experiments to confirm this association in humans and mice. The positive results inferred from <span class="math inline">\(p &lt; 0.05\)</span> led to follow-up experiments in Figures 2, 3, and 4.</li>
<li>(Figure 2) Experiments with <em>GDF15</em> knockout and <em>GFRAL</em> (the GDF15 receptor) knockout to probe if GDF15 is necessary for the metformin-associated weight loss, food intake reduction, and energy expenditure increase. The positive results inferred from <span class="math inline">\(p &lt; 0.05\)</span> led to the conclusion that GDF15 signaling is a mediator of metformin-induced weight loss via GDF15 signaling of both food intake and energy expenditure.</li>
<li>(Figure 3) Experiments with <em>GDF15</em> knockout and <em>GFRAL</em> (the GDF15 receptor) knockout to probe if GDF15 is necessary for metformin-associated regulation of glucose homeostasis. The negative results inferred from <span class="math inline">\(p &gt; 0.05\)</span> led to the conclusion that GDF15 signaling is a not a mediator of metformin-induced decreases in fasting glucose and insulin.</li>
<li>(Figure 4) Experiments to probe which tissues respond to metformin by upregulating <em>GDF15</em> expression. The positive results inferred from <span class="math inline">\(p &lt; 0.05\)</span> led to follup up, confirmatory experiments using alternative methods and tissue sources. The positive results inferred from <span class="math inline">\(p &lt; 0.05\)</span> in these original and follow up experiments led to the conclusion that metformin upregulates <em>GDF15</em> expression in the small intestine, colon, rectum, and kidney.</li>
</ol>
<p>The researchers are using the <em>p</em>-values as a tool not just to draw conclusions about effects and lack of effects but, importantly to identify follow-up experiments. And positive results (<span class="math inline">\(p &lt; 0.05\)</span>) in this publication will motivate this research group and others to execute follow-up experiments in future studies. Here, and in effectively all other experimental biology papers, <em>p</em>-values are not used in a Neyman-Pearson framework despite the ubiquitous statement “we consider <span class="math inline">\(p &lt; 0.05\)</span> to be significant” in the methods. Instead, smaller p-values seem to give the researchers greater confidence in the conclusion. And, the decision strategy seems to be, if the <em>p</em>-value is at least close to 0.05 and we expect a treatment effect given available information, any <em>p</em> value close to but not less than 0.05 is good enough to act as if there is an effect.</p>
<ul>
<li>abandon p-values and emphasize effect sizes and uncertainty. Problem is biological consequences of effect size is unknown and some assays use units in which effect sizes are meaningless.</li>
<li>abandon p-values in favor or model selection or model averaging</li>
<li>abandon frequentist statistics in favor of Bayesian methods. Not going to happen. Decisions still have to be made.</li>
<li>abandon decisions based on p-values for decisions based on Bayes factors</li>
<li>abandon “signficance”. Worry is that researchers will then claim effects when p = 0.1 or whatev. Who cares?</li>
<li>cost probably more to optimistic p-values due to pseudoreplication or not controlling for FDR or not sufficient replication, so continue as is but do better statistics.</li>
</ul>
</section>
<section id="better-reproducibility" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="better-reproducibility"><span class="header-section-number">6.10</span> Better reproducibility</h2>
<ol type="1">
<li>true randomization and selection, blind scoring</li>
<li>knowledge of statistics helps with experimental design</li>
<li>use best practice statistics especially accounting for pseudoreplication and blocking</li>
<li>combine experiments properly</li>
<li>experiments used to make decisions to move forward should 1) replicate experiments and 2) use conservative p-values (ideally results shouldn’t need a formal test)</li>
</ol>
<p>xxx finish section</p>
</section>
<section id="multiple-testing-and-controlling-for-false-positives" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="multiple-testing-and-controlling-for-false-positives"><span class="header-section-number">6.11</span> Multiple testing and controlling for false positives</h2>
<p>Bench biologists compute <em>a bunch</em> of <em>p</em>-values in every paper. For example, in a 2 x 2 factorial experiment (e.g.&nbsp;WT-Chow, WT-HFD, KO-Chow, KO-HFD), there are six differences between means (pairwise comparisons) plus an interaction effect. Researchers typically compute <em>p</em>-values for multiple measured outcomes per experiment. If there are 5 outcomes from a 2 x 2 factorial experiment, researchers might report 35 p-values. The number of potential p-values, can rise very quickly above this if one or more of the variables are measured at multiple time points, such as weekly body weight measurements over 12 weeks, or multiple glucose measurements over the 120 minute duration of a glucose tolerance test. And this is just Figure 1!</p>
<p>If these <em>p</em>-values are used to claim an effect (a discovery) or used to pursue a line of follow-up experiments, there will be multiple false positives. Here, I’ll define a false positive as either False positives lead to non-reproducible research. Researchers want to limit false positives because it is costly in both time and money to pursue lines of research based on a mistaken model of how something works. Exciting, positive results from one study spawn follow-up experiments not just by the original research team but also by other research groups. So, researchers want other researchers to limit false positives. And of course, funding agencies want researchers to limit false positives.</p>
<section id="controlling-the-family-wise-error-rate-when-all-tests-are-testing-the-same-hypothesis" class="level3" data-number="6.11.1">
<h3 data-number="6.11.1" class="anchored" data-anchor-id="controlling-the-family-wise-error-rate-when-all-tests-are-testing-the-same-hypothesis"><span class="header-section-number">6.11.1</span> Controlling the family-wise error rate when all tests are testing the same hypothesis</h3>
</section>
</section>
<section id="recommendations" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="recommendations"><span class="header-section-number">6.12</span> Recommendations</h2>
<ol type="1">
<li>Simply report the exact <em>p</em>-value, along with a CI of the estimate.</li>
</ol>
<ul>
<li><em>P</em>-values are noisy, there is little reason to report more than two significant digits (report “<span class="math inline">\(p = 0.011\)</span>” not “<span class="math inline">\(p = 0.0108\)</span>”) although some journals recommend more than two significant digits.</li>
<li>For high <em>p</em>-values, report “<span class="math inline">\(p = 0.23\)</span>” not “<span class="math inline">\(p = n.s.\)</span>”.</li>
<li>For small <em>p</em>-values, there is little reason to report more than one significant digit (report “<span class="math inline">\(p = 0.0002\)</span>” not “<span class="math inline">\(p = 0.00018\)</span>”).</li>
<li>For really small p-values, there is little reason to report the exact <em>p</em>-value (report “<span class="math inline">\(p &lt; 0.0001\)</span>” and not “<span class="math inline">\(p = 2.365E-11\)</span>”). Recognize that “really small” is entirely arbitrary. Rafael Irizarry suggested that <em>p</em>-values less than something like the probability of being killed by lightning strike should be reported as “<span class="math inline">\(p &lt; m\)</span>”, where <span class="math inline">\(m\)</span> is the probability of being killed by lightning strike<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. According Google University, this is 0.00000142 in one year or 0.00033 in one lifetime. This text will use <span class="math inline">\(p &lt; ls\)</span>” for <em>p</em>-values less than 0.0001 – the lifetime probability of being killed by lightning strike in someone that spends too much time indoors analyzing data.</li>
</ul>
<ol start="2" type="1">
<li>If <span class="math inline">\(p &lt; 0.05\)</span> (or some other <span class="math inline">\(\alpha\)</span>) do not report this as “significant” – in fact, avoid the word “significant”. In the english language, “significant” implies big or important. Small <em>p</em>-values can result even with trivially small effects if <span class="math inline">\(n\)</span> is big or sample variation is small. The phrase “ASK1 knockout had a significant effect on reducing liver TG (<span class="math inline">\(p = 0.011\)</span>)” is</li>
</ol>
<ul>
<li>potentially misleading, if we interpret “significant” to mean “having a large effect on the regulation of liver TG”,</li>
<li>wrong, if we interpret “significant” to mean “there is an ASK1 knockout effect”. A low <em>p</em>-value is evidence that the effect of ASK1 knockout is not zero, but I would wager that knocking out any gene expressed in white adipose cells will have <em>some</em> effect (however small) on liver TG.</li>
</ul>
<ol start="3" type="1">
<li>If a decision needs to be made (“do we devote time, expense, and personel to pursue this further?”), then a <em>p</em>-value is a useful tool. If <em>p</em> is smaller than say 0.001, this is pretty good evidence that the data is not a fluke of sampling, <strong>as long as we are justifiably confident in all the assumptions that went into computing this <em>p</em>-value</strong>. A replicate experiment with a small <em>p</em>-value is better evidence. If <em>p</em> is closer to 0.01 or 0.05, this is only weak evidence of a fluke because of the sampling variability of <em>p</em>. A replicate experiment with a small <em>p</em>-value is <em>much</em> better evidence.</li>
</ol>
<section id="primary-sources-for-recommendations" class="level3" data-number="6.12.1">
<h3 data-number="6.12.1" class="anchored" data-anchor-id="primary-sources-for-recommendations"><span class="header-section-number">6.12.1</span> Primary sources for recommendations</h3>
<ol type="1">
<li><a href="https://link.springer.com/article/10.1007/s10654-016-0149-3">Statistical tests, P values, confidence intervals, and power: a guide to misinterpretations</a>.</li>
<li>“Q: Why do so many colleges and grad schools teach p = 0.05? A: Because that’s still what the scientific community and journal editors use. Q: Why do so many people still use p = 0.05? A: Because that’s what they were taught in college or grad school.” – <a href="https://amstat.tandfonline.com/doi/full/10.1080/00031305.2016.1154108">ASA Statement on Statistical Significance and P-Values</a></li>
<li>“We then discuss our own proposal, which is to abandon statistical significance. We recommend dropping the NHST paradigm—and the p-value thresholds intrinsic to it—as the default statistical paradigm for research, publication, and discovery in the biomedical and social sciences.” – <a href="https://www.tandfonline.com/doi/abs/10.1080/00031305.2018.1527253">Abandon Statistical Significance</a></li>
<li>“We conclude, based on our review of the articles in this special issue and the broader literature, that it is time to stop using the term “statistically significant” entirely. Nor should variants such as “significantly different,” “<span class="math inline">\(p&lt;0.05\)</span>,” and “nonsignificant” survive, whether expressed in words, by asterisks in a table, or in some other way.” – <a href="https://www.tandfonline.com/doi/full/10.1080/00031305.2019.1583913">Moving to a World Beyond “p &lt; 0.05”</a></li>
<li>“We agree, and call for the entire concept of statistical significance to be abandoned.”–<a href="https://www.nature.com/articles/d41586-019-00857-9">Scientists rise up against statistical significance</a></li>
</ol>
</section>
</section>
<section id="problems" class="level2" data-number="6.13">
<h2 data-number="6.13" class="anchored" data-anchor-id="problems"><span class="header-section-number">6.13</span> Problems</h2>
<p>Problem 1 – simulate the distribution of <em>p</em> under the null. There are many ways to do this but a straightforard approach is to</p>
<ol type="1">
<li>Create a <span class="math inline">\(2n \times m\)</span> matrix of random normal deviates with mean 0 and sd 1</li>
<li>Do a <em>t</em>-test on each column, with the first <span class="math inline">\(n\)</span> values assigned to one group and the remaining <span class="math inline">\(n\)</span> values assigned to the second group. Save the <em>p</em>-value from each.</li>
<li>Plot a histogram of the <em>p</em>-values.</li>
<li>What is the distribution? What is the most likely value of <em>p</em>?</li>
</ol>
<p>Problem 2 – simulate power. Again, many ways to do this but following up on Problem 1. 1. Create a <span class="math inline">\(2n \times m\)</span> matrix of random normal deviates with mean 0 and sd 1 2. Add an effect to the first <span class="math inline">\(n\)</span> values of each column. Things to think about a. what is a good effect size to add? The effect/sd ratio, known as Cohen’s d, is a relative (or standardized) measure of effect size. Cohen suggest 0.2, 0.5, and 0.8 as small, medium, and large standardized effects. b. should the same effect be added to each individual? Yes! It is the random component that captures the individual variation in the response. 3. Do a <em>t</em>-test on each column of the matrix, using the first <span class="math inline">\(n\)</span> values in group 1 and the remaining <span class="math inline">\(n\)</span> values in group 2. Save the p-values for each. 4. Compute the power, the relative frequency <span class="math inline">\(p \le 0.05\)</span>. 5. Repeat with different values of <span class="math inline">\(n\)</span>, effect size, and sd, but only vary one at a time. How does power vary with these three parameters?</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Amrhein, V., Trafimow, D. and Greenland, S., 2019. Inferential statistics as descriptive statistics: There is no replication crisis if we don’t expect replication. The American Statistician, 73(sup1), pp.262-270.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>https://twitter.com/rafalab/status/1310610623898808320<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/uncertainty-sd-and-se.html" class="pagination-link" aria-label="Variability and Uncertainty (Standard Deviations, Standard Errors, and Confidence Intervals)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Variability and Uncertainty (Standard Deviations, Standard Errors, and Confidence Intervals)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/inference-errors.html" class="pagination-link" aria-label="Errors in inference">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Errors in inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>