---
title: "GLM Count Simulation"
author: "Jeffrey Walker"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(MASS)
library(glmmTMB)
library(gamlss)
library(moments) # skewness
library(performance) # model checks
library(DHARMa)
library(AICcmodavg) # qaic
library(knitr)
library(kableExtra)
ggplot_the_model_path <- here::here("R/ggplot_the_model.R")
source(ggplot_the_model_path)

```

```{r rqpois}
  rqpois <- function(n, mu, theta) {
    # theta is the qp dispersion parameter which > 1
    # theta = 1 = poisson
    y <- rnbinom(n = n, mu = mu, size = mu/(theta-1))
    return(y)
  }
```


```{r fqaic}
fqaic <- function(model) {
  loglik <- sum(dpois(model$y, model$fitted.values, log = TRUE))
  phi <- summary(model)$dispersion
  qaic <- -2*loglik/phi + 2*summary(model)$df[3]
  qaic <- -2*loglik + 2*summary(model)$df[3] * phi
  return(qaic)
}
```


```{r pless, echo=FALSE}
  pless <- function(x){
    value <- sum(x < 0.05, na.rm=TRUE)/length(na.omit(x))
    return(value)
  }

```


```{r simulation-3x, fig.width=8, fig.height = 4, warning=FALSE}
# https://stats.stackexchange.com/questions/71519/when-do-poisson-and-negative-binomial-regressions-fit-the-same-coefficients
n_iter <- 500
set.seed(3)
file_path <- "glm_3x_results_new_lrt_out.Rds"
do_it <- TRUE
if(do_it){
  
  # variable parameters
  model_list <- c("qp", "nb") # generating model for count data
  n_list <- c(6, 20)
  theta_list <- c(1, 5)
  unbalanced <- FALSE    
  parameter_matrix <- expand.grid(theta = theta_list,
                                  model = model_list,
                                  sample_size = n_list)
  results_out <- data.table(NULL)
  
  mag <- 1
  mu_ref <- 10 # mu[3] is modified in the loop
  k <- 3
  
  model_summary_matrix_labels <- c("skew_lm1", "aic_lm", "aic_nb1", "aic_nb2", "aic_nb1_pw", "aic_nb2_pw")
  model_summary_matrix <- matrix(nrow = n_iter,
                         ncol = length(model_summary_matrix_labels))
  colnames(model_summary_matrix) <- model_summary_matrix_labels
  
  stats_labels <- c("lm_mu1", "lm_mu2", "lm_b1", "lm_p",
                    "gls_mu1", "gls_mu2", "gls_b1", "gls_p",
                    "lm_log_mu1", "lm_log_mu2", "lm_log_b1", "lm_log_p",
                    "qp_mu1", "qp_mu2", "qp_b1", "qp_p",
                    "nb1_mu1", "nb1_mu2", "nb1_b1", "nb1_p",# "nb1_lrt_p",
                    "nb2_mu1", "nb2_mu2", "nb2_b1", "nb2_p",# "nb2_lrt_p",
                    "nb1_pw_mu1", "nb1_pw_mu2", "nb1_pw_b1", "nb1_pw_p", "nb1_pw_lrt_p",
                    "nb2_pw_mu1", "nb2_pw_mu2", "nb2_pw_b1", "nb2_pw_p", "nb2_pw_lrt_p",
                    "nb1b_mu1", "nb1b_mu2", "nb1b_b1", "nb1b_p",
                    "nb2b_mu1", "nb2b_mu2", "nb2b_b1", "nb2b_p",
                    "mw")
  
  type1_matrix <- matrix(nrow = n_iter,
                         ncol = length(stats_labels))
  power_matrix <- matrix(nrow = n_iter,
                         ncol = length(stats_labels))
  colnames(type1_matrix) <- stats_labels
  colnames(power_matrix) <- stats_labels
  
  mu_mag <- c(3.1, 2.0, 4.2, 2.2, 2.0, 1.5, 2.4, 1.6) #9
  for(parameter_set in 1:nrow(parameter_matrix)){
    # if(parameter_set %in% c(1:4,6:8)){
    #   next()
    # }
    gen_theta <- parameter_matrix[parameter_set, "theta"]
    gen_model <- parameter_matrix[parameter_set, "model"]
    n <- parameter_matrix[parameter_set, "sample_size"]
    mu_sim <- rep(mu_ref, 3)
    row_i <- row.names(parameter_matrix)[parameter_set]
    mu_sim[3] <- mu_mag[parameter_set] * mu_sim[1]
 
    if(unbalanced == TRUE){
      if(n == 6){
        n_vec <- c(4,6,8)
        n_vec <- c(8,6,4)
      }
      if(n == 20){
        n_vec <- c(14,20,26)
        n_vec <- c(26,20,14)
      }
    }else{
      n_vec <- c(n, n, n)
    }
    N <- sum(n_vec)
    fd <- data.table(
      genotype = rep(c("WT", "KO", "TR"), n_vec) |>
        factor(levels = c("WT", "KO", "TR"))
    )

    # nb var = mu + mu^2/theta
    # qp var = theta*mu
    # qp*mu = mu + mu^2/nb
    # qp = mu/mu + mu^2/nb
    # qp = 1 + mu/nb
    # if nb = 0.5 qp and mu = 10 then qp = 21
    # if nb = 2 qp and mu = 10 then qp = 6
    theta_nb <- gen_theta
    theta_qp <- 1 + mu_sim/theta_nb
    if(gen_model == "qp"){
      y_qp <- rqpois(n * k * n_iter,
                     mu = rep(mu_sim, n_vec),
#                     theta = rep(theta_qp, n_vec),
                     theta = theta_qp[1]
                     )
      y_mat <- matrix(y_qp, nrow = n * k, ncol = n_iter)
    }
    if(gen_model == "nb"){
      y_nb <- rnegbin(n * k * n_iter,
                      mu = rep(mu_sim, n_vec),
                      theta = theta_nb)
      y_mat <- matrix(y_nb, nrow = n * k, ncol = n_iter)
    }
    
    for(iter in 1:n_iter){
      fd[, tumors := y_mat[, iter]]
      lm1 <- lm(tumors ~ genotype,
                data = fd)
      lm1_log <- lm(log(tumors + 1) ~ genotype,
                    data = fd)
      gls1 <- gls(tumors ~ genotype,
                weights = varIdent(form = ~ 1 | genotype),
                data = fd)
      pois1 <- glm(tumors ~ genotype,
                 family = poisson(link = "log"),
                 data = fd)
      qp1 <- glm(tumors ~ genotype,
                 family = quasipoisson(link = "log"),
                 data = fd)
      nb1 <- glmmTMB(tumors ~ genotype,
                     family = nbinom1(link = "log"),
                     data = fd)
      nb2 <- glmmTMB(tumors ~ genotype,
                     family = nbinom2(link = "log"),
                     data = fd)
      nb1b <- try(gamlss(tumors ~ genotype, 
                         sigma.formula = ~ genotype, 
                         family = NBII, 
                         mu.link = "log", 
                         sigma.link = "log",
                         data = fd,
                         trace=FALSE),
                  silent = TRUE)
      if(inherits(nb1b, "try-error") == TRUE){
        nb1b <- nb1
      }

      nb2b <- try(gamlss(tumors ~ genotype, 
                         sigma.formula = ~ genotype, 
                         family = NBII, 
                         mu.link = "log", 
                         sigma.link = "log",
                         data = fd,
                         trace=FALSE),
                  silent = TRUE)
      if(inherits(nb2b, "try-error") == TRUE){
        nb2b <- nb2
      }

      # pairwise models
      nb1_pw_1 <- glmmTMB(tumors ~ genotype,  # the type 1 pair
                          family = nbinom1(link = "log"),
                          data = fd[genotype %in% c("WT", "KO"),])
      nb1_pw_2 <- glmmTMB(tumors ~ genotype,  # the power pair
                          family = nbinom1(link = "log"),
                          data = fd[genotype %in% c("WT", "TR"),])
      nb2_pw_1 <- glmmTMB(tumors ~ genotype,  # the type 1 pair
                          family = nbinom2(link = "log"),
                          data = fd[genotype %in% c("WT", "KO"),])
      nb2_pw_2 <- glmmTMB(tumors ~ genotype,  # the power pair
                          family = nbinom2(link = "log"),
                          data = fd[genotype %in% c("WT", "TR"),])
      # Mann-Whitney-Wilcoxan
      mww1 <- wilcox.test(tumors ~ genotype,
                          data = fd[genotype %in% c("WT", "KO"),])$p.value
      mww2 <- wilcox.test(tumors ~ genotype,
                          data = fd[genotype %in% c("WT", "TR"),])$p.value
      
      # statistics
      model_summary_matrix[iter, "skew_lm1"] <- skewness(residuals(lm1))
      model_summary_matrix[iter, "aic_lm"] <- AIC(lm1)
      model_summary_matrix[iter, "aic_nb1"] <- AIC(nb1)
      model_summary_matrix[iter, "aic_nb2"] <- AIC(nb2)
      model_summary_matrix[iter, "aic_nb1_pw"] <- AIC(nb1_pw_2)
      model_summary_matrix[iter, "aic_nb2_pw"] <- AIC(nb2_pw_2)
      
      # type 1
      nonref <- 2
      type1_matrix[iter, "lm_mu1"] <- coef(lm1)[1]
      type1_matrix[iter, "lm_mu2"] <- coef(lm1)[1] + coef(lm1)[nonref]
      type1_matrix[iter, "lm_b1"] <- coef(lm1)[nonref]
      type1_matrix[iter, "lm_p"] <- summary(contrast(emmeans(lm1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      type1_matrix[iter, "gls_mu1"] <- coef(gls1)[1]
      type1_matrix[iter, "gls_mu2"] <- coef(gls1)[1] + coef(gls1)[nonref]
      type1_matrix[iter, "gls_b1"] <- coef(gls1)[nonref]
      type1_matrix[iter, "gls_p"] <- summary(contrast(emmeans(gls1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      type1_matrix[iter, "lm_log_mu1"] <- coef(lm1_log)[1]
      type1_matrix[iter, "lm_log_mu2"] <- coef(lm1_log)[1] + coef(lm1_log)[nonref]
      type1_matrix[iter, "lm_log_b1"] <- coef(lm1_log)[nonref]
      type1_matrix[iter, "lm_log_p"] <- summary(contrast(emmeans(lm1_log, specs = "genotype"),
                                                         method = "revpairwise",
                                                         adjust = "none"))[nonref-1,"p.value"]
      
      type1_matrix[iter, "qp_mu1"] <- coef(qp1)[1]
      type1_matrix[iter, "qp_mu2"] <- coef(qp1)[1] + coef(qp1)[nonref]
      type1_matrix[iter, "qp_b1"] <- coef(qp1)[nonref]
      type1_matrix[iter, "qp_p"] <- summary(contrast(emmeans(qp1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      type1_matrix[iter, "nb1_mu1"] <- coef(summary(nb1))$cond[1,"Estimate"]
      type1_matrix[iter, "nb1_mu2"] <- coef(summary(nb1))$cond[1,"Estimate"] +
        coef(summary(nb1))$cond[nonref,"Estimate"]
      type1_matrix[iter, "nb1_b1"] <- coef(summary(nb1))$cond[nonref,"Estimate"]
      type1_matrix[iter, "nb1_p"] <- summary(contrast(
        emmeans(nb1, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[nonref-1,"p.value"]
      # type1_matrix[iter, "nb1_lrt_p"] <- anova(nb1_full, nb1_KO,
      #                                          test="Chisq")$"Pr(>Chisq)"[2]
      
      type1_matrix[iter, "nb2_mu1"] <- coef(summary(nb2))$cond[1,"Estimate"]
      type1_matrix[iter, "nb2_mu2"] <- coef(summary(nb2))$cond[1,"Estimate"] +
        coef(summary(nb2))$cond[nonref,"Estimate"]
      type1_matrix[iter, "nb2_b1"] <- coef(summary(nb2))$cond[nonref,"Estimate"]
      type1_matrix[iter, "nb2_p"] <- summary(contrast(
        emmeans(nb2, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[nonref-1,"p.value"]
      # type1_matrix[iter, "nb2_lrt_p"] <- anova(nb2_full, nb2_KO,
      #                                          test="Chisq")$"Pr(>Chisq)"[2]
     
      type1_matrix[iter, "nb1_pw_mu1"] <- coef(summary(nb1_pw_1))$cond[1,"Estimate"]
      type1_matrix[iter, "nb1_pw_mu2"] <- coef(summary(nb1_pw_1))$cond[1,"Estimate"] +
        coef(summary(nb1))$cond[nonref,"Estimate"]
      type1_matrix[iter, "nb1_pw_b1"] <- coef(summary(nb1_pw_1))$cond[2,"Estimate"]
      type1_matrix[iter, "nb1_pw_p"] <- summary(contrast(
        emmeans(nb1_pw_1, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[1,"p.value"]
      type1_matrix[iter, "nb1_pw_lrt_p"] <- drop1(nb1_pw_1, test="Chisq")$"Pr(>Chi)"[2]

      type1_matrix[iter, "nb2_pw_mu1"] <- coef(summary(nb2_pw_1))$cond[1,"Estimate"]
      type1_matrix[iter, "nb2_pw_mu2"] <- coef(summary(nb2_pw_1))$cond[1,"Estimate"] +
        coef(summary(nb2))$cond[nonref,"Estimate"]
      type1_matrix[iter, "nb2_pw_b1"] <- coef(summary(nb2_pw_1))$cond[2,"Estimate"]
      type1_matrix[iter, "nb2_pw_p"] <- summary(contrast(
        emmeans(nb2_pw_1, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[1,"p.value"]
      type1_matrix[iter, "nb2_pw_lrt_p"] <- drop1(nb2_pw_1, test="Chisq")$"Pr(>Chi)"[2]
      
      type1_matrix[iter, "mw"] <- mww1

      
      # power
      nonref <- 3
      power_matrix[iter, "lm_mu1"] <- coef(lm1)[1]
      power_matrix[iter, "lm_mu2"] <- coef(lm1)[1] + coef(lm1)[nonref]
      power_matrix[iter, "lm_b1"] <- coef(lm1)[nonref]
      power_matrix[iter, "lm_p"] <- summary(contrast(emmeans(lm1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      power_matrix[iter, "gls_mu1"] <- coef(gls1)[1]
      power_matrix[iter, "gls_mu2"] <- coef(gls1)[1] + coef(gls1)[nonref]
      power_matrix[iter, "gls_b1"] <- coef(gls1)[nonref]
      power_matrix[iter, "gls_p"] <- summary(contrast(emmeans(gls1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      power_matrix[iter, "lm_log_mu1"] <- coef(lm1_log)[1]
      power_matrix[iter, "lm_log_mu2"] <- coef(lm1_log)[1] + coef(lm1_log)[nonref]
      power_matrix[iter, "lm_log_b1"] <- coef(lm1_log)[nonref]
      power_matrix[iter, "lm_log_p"] <- summary(contrast(emmeans(lm1_log, specs = "genotype"),
                                                         method = "revpairwise",
                                                         adjust = "none"))[nonref-1,"p.value"]
      
      power_matrix[iter, "qp_mu1"] <- coef(qp1)[1]
      power_matrix[iter, "qp_mu2"] <- coef(qp1)[1] + coef(qp1)[nonref]
      power_matrix[iter, "qp_b1"] <- coef(qp1)[nonref]
      power_matrix[iter, "qp_p"] <- summary(contrast(emmeans(qp1, specs = "genotype"),
                                                     method = "revpairwise",
                                                     adjust = "none"))[nonref-1,"p.value"]
      
      power_matrix[iter, "nb1_mu1"] <- coef(summary(nb1))$cond[1,"Estimate"]
      power_matrix[iter, "nb1_mu2"] <- coef(summary(nb1))$cond[1,"Estimate"] +
        coef(summary(nb1))$cond[nonref,"Estimate"]
      power_matrix[iter, "nb1_b1"] <- coef(summary(nb1))$cond[nonref,"Estimate"]
      power_matrix[iter, "nb1_p"] <- summary(contrast(
        emmeans(nb1, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[nonref-1,"p.value"]
      # power_matrix[iter, "nb1_lrt_p"] <- anova(nb1_full, nb1_Tr, test="Chisq")$"Pr(>Chisq)"[2]
      
      power_matrix[iter, "nb2_mu1"] <- coef(summary(nb2))$cond[1,"Estimate"]
      power_matrix[iter, "nb2_mu2"] <- coef(summary(nb2))$cond[1,"Estimate"] +
        coef(summary(nb2))$cond[nonref,"Estimate"]
      power_matrix[iter, "nb2_b1"] <- coef(summary(nb2))$cond[nonref,"Estimate"]
      power_matrix[iter, "nb2_p"] <- summary(contrast(
        emmeans(nb2, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[nonref-1,"p.value"]
      # power_matrix[iter, "nb2_lrt_p"] <- anova(nb2_full, nb2_Tr, test="Chisq")$"Pr(>Chisq)"[2]
      
      power_matrix[iter, "nb1_pw_mu1"] <- coef(summary(nb1_pw_2))$cond[1,"Estimate"]
      power_matrix[iter, "nb1_pw_mu2"] <- coef(summary(nb1_pw_2))$cond[1,"Estimate"] +
        coef(summary(nb1))$cond[nonref,"Estimate"]
      power_matrix[iter, "nb1_pw_b1"] <- coef(summary(nb1_pw_2))$cond[2,"Estimate"]
      power_matrix[iter, "nb1_pw_p"] <- summary(contrast(
        emmeans(nb1_pw_2, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[1,"p.value"]
      power_matrix[iter, "nb1_pw_lrt_p"] <- drop1(nb1_pw_2,
                                                  test="Chisq")$"Pr(>Chi)"[2]
      
      power_matrix[iter, "nb2_pw_mu1"] <- coef(summary(nb2_pw_2))$cond[1,"Estimate"]
      power_matrix[iter, "nb2_pw_mu2"] <- coef(summary(nb2_pw_2))$cond[1,"Estimate"] +
        coef(summary(nb2))$cond[nonref,"Estimate"]
      power_matrix[iter, "nb2_pw_b1"] <- coef(summary(nb2_pw_2))$cond[2,"Estimate"]
      power_matrix[iter, "nb2_pw_p"] <- summary(contrast(
        emmeans(nb2_pw_2, specs = "genotype"), method = "revpairwise",
        adjust = "none"))[1,"p.value"]
      power_matrix[iter, "nb2_pw_lrt_p"] <- drop1(nb2_pw_2,
                                                  test="Chisq")$"Pr(>Chi)"[2]
    
      power_matrix[iter, "mw"] <- mww2

      # gamlss type 1 and power
      nb1b_emm <- try(emmeans(nb1b, specs = "genotype"),
                      silent = TRUE)
      if(inherits(nb1b_emm, "try-error") == TRUE){
        nonref <- 2
        type1_matrix[iter, "nb1b_mu1"] <- type1_matrix[iter, "nb1_mu1"]
        type1_matrix[iter, "nb1b_mu2"] <- type1_matrix[iter, "nb1_mu2"]
        type1_matrix[iter, "nb1b_b1"] <- type1_matrix[iter, "nb1_b1"]
        type1_matrix[iter, "nb1b_p"] <- type1_matrix[iter, "nb1_p"]
        nonref <- 3
        power_matrix[iter, "nb1b_mu1"] <- power_matrix[iter, "nb1_mu1"]
        power_matrix[iter, "nb1b_mu2"] <- power_matrix[iter, "nb1_mu2"]
        power_matrix[iter, "nb1b_b1"] <- power_matrix[iter, "nb1_b1"]
        power_matrix[iter, "nb1b_p"] <- power_matrix[iter, "nb1_p"]
      }else{
        nb1b_pairs <- contrast(nb1b_emm, method = "revpairwise", adjust = "none")
        nonref <- 2
        type1_matrix[iter, "nb1b_mu1"] <- summary(nb1b_emm)[1,"emmean"]
        type1_matrix[iter, "nb1b_mu2"] <- summary(nb1b_emm)[nonref,"emmean"]
        type1_matrix[iter, "nb1b_b1"] <- summary(nb1b_pairs)[nonref-1, "estimate"]
        type1_matrix[iter, "nb1b_p"] <- summary(nb1b_pairs)[nonref-1, "p.value"]
        nonref <- 3
        power_matrix[iter, "nb1b_mu1"] <- summary(nb1b_emm)[1,"emmean"]
        power_matrix[iter, "nb1b_mu2"] <- summary(nb1b_emm)[nonref,"emmean"]
        power_matrix[iter, "nb1b_b1"] <- summary(nb1b_pairs)[nonref-1, "estimate"]
        power_matrix[iter, "nb1b_p"] <- summary(nb1b_pairs)[nonref-1, "p.value"]
      }
      
      nb2b_emm <- try(emmeans(nb2b, specs = "genotype"),
                      silent = TRUE)
      if(inherits(nb2b_emm, "try-error") == TRUE){
        nonref <- 2
        type1_matrix[iter, "nb2b_mu1"] <- type1_matrix[iter, "nb2_mu1"]
        type1_matrix[iter, "nb2b_mu2"] <- type1_matrix[iter, "nb2_mu2"]
        type1_matrix[iter, "nb2b_b1"] <- type1_matrix[iter, "nb2_b1"]
        type1_matrix[iter, "nb2b_p"] <- type1_matrix[iter, "nb2_p"]
        nonref <- 3
        power_matrix[iter, "nb2b_mu1"] <- power_matrix[iter, "nb2_mu1"]
        power_matrix[iter, "nb2b_mu2"] <- power_matrix[iter, "nb2_mu2"]
        power_matrix[iter, "nb2b_b1"] <- power_matrix[iter, "nb2_b1"]
        power_matrix[iter, "nb2b_p"] <- power_matrix[iter, "nb2_p"]
      }else{
        nb2b_pairs <- contrast(nb2b_emm, method = "revpairwise", adjust = "none")
        nonref <- 2
        type1_matrix[iter, "nb2b_mu1"] <- summary(nb2b_emm)[1,"emmean"]
        type1_matrix[iter, "nb2b_mu2"] <- summary(nb2b_emm)[nonref,"emmean"]
        type1_matrix[iter, "nb2b_b1"] <- summary(nb2b_pairs)[nonref-1, "estimate"]
        type1_matrix[iter, "nb2b_p"] <- summary(nb2b_pairs)[nonref-1, "p.value"]
        nonref <- 3
        power_matrix[iter, "nb2b_mu1"] <- summary(nb2b_emm)[1,"emmean"]
        power_matrix[iter, "nb2b_mu2"] <- summary(nb2b_emm)[nonref,"emmean"]
        power_matrix[iter, "nb2b_b1"] <- summary(nb2b_pairs)[nonref-1, "estimate"]
        power_matrix[iter, "nb2b_p"] <- summary(nb2b_pairs)[nonref-1, "p.value"]
      }

    }
    results_out <- rbind(
      results_out,
      data.table(
        theta = gen_theta,
        model = gen_model,
        sample_size = n,
        type = "type1",
        type1_matrix,
        model_summary_matrix
      ),
      data.table(
        theta = gen_theta,
        model = gen_model,
        sample_size = n,
        type = "power",
        power_matrix,
        model_summary_matrix
      )
    )
  }
  
  saveRDS(results_out, file_path)
  
}


results_out <- readRDS(file_path)
# results_out <- readRDS("glm_3x_results_balanced.Rds")


# print results
theta_list <- c(1, 5)
model_list <- c("qp", "nb")
n_list <- c(6, 20)
type_list <- c("type1", "power")
  
parameter_matrix <- expand.grid(theta = theta_list,
                                model = model_list,
                                sample_size = n_list,
                                sim_type = type_list)

stats_labels <- c("lm_mu1", "lm_mu2", "lm_b1", "lm_p",
                  "gls_mu1", "gls_mu2", "gls_b1", "gls_p",
                  "lm_log_mu1", "lm_log_mu2", "lm_log_b1", "lm_log_p",
                  "qp_mu1", "qp_mu2", "qp_b1", "qp_p",
                  "nb1_mu1", "nb1_mu2", "nb1_b1", "nb1_p",# "nb1_lrt_p",
                  "nb2_mu1", "nb2_mu2", "nb2_b1", "nb2_p",# "nb2_lrt_p",
                  "nb1_pw_mu1", "nb1_pw_mu2", "nb1_pw_b1", "nb1_pw_p", "nb1_pw_lrt_p",
                  "nb2_pw_mu1", "nb2_pw_mu2", "nb2_pw_b1", "nb2_pw_p", "nb2_pw_lrt_p",
                  "nb1b_mu1", "nb1b_mu2", "nb1b_b1", "nb1b_p",
                  "nb2b_mu1", "nb2b_mu2", "nb2b_b1", "nb2b_p",
                  "mw")
stats_matrix <- matrix(nrow = n_iter,
                       ncol = length(stats_labels))
colnames(stats_matrix) <- stats_labels

summary_table <- data.table(NULL)
for(parameter_set in 1:nrow(parameter_matrix)){
  gen_theta <- parameter_matrix[parameter_set, "theta"]
  gen_model <- parameter_matrix[parameter_set, "model"]
  sim_type <- parameter_matrix[parameter_set, "sim_type"]
  n <- parameter_matrix[parameter_set, "sample_size"] 
  stats_matrix <- results_out[theta == gen_theta & 
                                model == gen_model &
                                type == sim_type &
                                sample_size == n,
                              .SD,
                              .SDcols = stats_labels] |>
    as.matrix()
  model_summary_matrix <- results_out[theta == gen_theta & 
                                model == gen_model &
                                type == sim_type &
                                sample_size == n,
                              .SD,
                              .SDcols = model_summary_matrix_labels] |>
    as.matrix()
  
  lm_mu1 <- mean(stats_matrix[, "lm_mu1"])
  lm_mu2 <- mean(stats_matrix[, "lm_mu2"])
  lm_effect <- mean(stats_matrix[, "lm_b1"])
  lm_sd_b1 <- sd(stats_matrix[, "lm_b1"])
  lm_pless <- pless(stats_matrix[, "lm_p"])
  
  gls_mu1 <- mean(stats_matrix[, "gls_mu1"])
  gls_mu2 <- mean(stats_matrix[, "gls_mu2"])
  gls_effect <- mean(stats_matrix[, "gls_b1"])
  gls_sd_b1 <- sd(stats_matrix[, "gls_b1"])
  gls_pless <- pless(stats_matrix[, "gls_p"])
  
  lm_log_mu1 <- mean(exp(stats_matrix[, "lm_log_mu1"]))
  lm_log_mu2 <- mean(exp(stats_matrix[, "lm_log_mu2"]))
  lm_log_effect <- mean(exp(stats_matrix[, "lm_log_b1"]))
  lm_log_sd_b1 <- sd(stats_matrix[, "lm_log_b1"])
  lm_log_pless <- pless(stats_matrix[, "lm_log_p"])
  
  qp_mu1 <- mean(exp(stats_matrix[, "qp_mu1"]))
  qp_mu2 <- mean(exp(stats_matrix[, "qp_mu2"]))
  qp_effect <- mean(exp(stats_matrix[, "qp_b1"]))
  qp_sd_b1 <- sd(stats_matrix[, "qp_b1"])
  qp_pless <- pless(stats_matrix[, "qp_p"])
  
  nb1_mu1 <- mean(exp(stats_matrix[, "nb1_mu1"]))
  nb1_mu2 <- mean(exp(stats_matrix[, "nb1_mu2"]))
  nb1_effect <- mean(exp(stats_matrix[, "nb1_b1"]))
  nb1_sd_b1 <- sd(stats_matrix[, "nb1_b1"])
  nb1_pless <- pless(stats_matrix[, "nb1_p"])

  nb2_mu1 <- mean(exp(stats_matrix[, "nb2_mu1"]))
  nb2_mu2 <- mean(exp(stats_matrix[, "nb2_mu2"]))
  nb2_effect <- mean(exp(stats_matrix[, "nb2_b1"]))
  nb2_sd_b1 <- sd(stats_matrix[, "nb2_b1"])
  nb2_pless <- pless(stats_matrix[, "nb2_p"])
  
  nb1_pw_mu1 <- mean(exp(stats_matrix[, "nb1_pw_mu1"]))
  nb1_pw_mu2 <- mean(exp(stats_matrix[, "nb1_pw_mu2"]))
  nb1_pw_effect <- mean(exp(stats_matrix[, "nb1_pw_b1"]))
  nb1_pw_sd_b1 <- sd(stats_matrix[, "nb1_pw_b1"])
  nb1_pw_pless <- pless(stats_matrix[, "nb1_pw_p"])
  
  nb2_pw_mu1 <- mean(exp(stats_matrix[, "nb2_pw_mu1"]))
  nb2_pw_mu2 <- mean(exp(stats_matrix[, "nb2_pw_mu2"]))
  nb2_pw_effect <- mean(exp(stats_matrix[, "nb2_pw_b1"]))
  nb2_pw_sd_b1 <- sd(stats_matrix[, "nb2_pw_b1"])
  nb2_pw_pless <- pless(stats_matrix[, "nb2_pw_p"])
  
  nb1_pw_lrt_mu1 <- nb1_pw_mu1
  nb1_pw_lrt_mu2 <- nb1_pw_mu2
  nb1_pw_lrt_effect <- nb1_pw_effect
  nb1_pw_lrt_sd_b1 <- nb1_pw_sd_b1
  nb1_pw_lrt_pless <- pless(stats_matrix[, "nb1_pw_lrt_p"])
  
  nb2_pw_lrt_mu1 <- nb2_pw_mu1
  nb2_pw_lrt_mu2 <- nb2_pw_mu2
  nb2_pw_lrt_effect <- nb2_pw_effect
  nb2_pw_lrt_sd_b1 <- nb2_pw_sd_b1
  nb2_pw_lrt_pless <- pless(stats_matrix[, "nb2_pw_lrt_p"])

  nb1b_mu1 <- mean(exp(stats_matrix[, "nb1b_mu1"]))
  nb1b_mu2 <- mean(exp(stats_matrix[, "nb1b_mu2"]))
  nb1b_effect <- mean(exp(stats_matrix[, "nb1b_b1"]))
  nb1b_sd_b1 <- sd(stats_matrix[, "nb1b_b1"])
  nb1b_pless <- pless(stats_matrix[, "nb1b_p"])

  nb2b_mu1 <- mean(exp(stats_matrix[, "nb2b_mu1"]))
  nb2b_mu2 <- mean(exp(stats_matrix[, "nb2b_mu2"]))
  nb2b_effect <- mean(exp(stats_matrix[, "nb2b_b1"]))
  nb2b_sd_b1 <- sd(stats_matrix[, "nb2b_b1"])
  nb2b_pless <- pless(stats_matrix[, "nb2b_p"])

  mw_mu1 <- NA
  mw_mu2 <- NA
  mw_effect <- NA
  mw_sd_b1 <- NA
  mw_pless <- pless(stats_matrix[, "mw"])
  
  glm_p <- numeric(nrow(model_summary_matrix))
  glm_pw_p <- numeric(nrow(model_summary_matrix))
  for(j in 1:nrow(model_summary_matrix)){
    glm_p[j] <- ifelse(model_summary_matrix[j, "aic_nb1"] < model_summary_matrix[j, "aic_nb2"], 
                    stats_matrix[j, "nb1_p"],
                    stats_matrix[j, "nb2_p"])
    glm_pw_p[j] <- ifelse(model_summary_matrix[j, "aic_nb1_pw"] < model_summary_matrix[j, "aic_nb2_pw"], 
                    stats_matrix[j, "nb1_pw_p"],
                    stats_matrix[j, "nb2_pw_p"])
  }
  nb1_nb2_pless <- pless(glm_p)
  nb1_nb2_pw_pless <- pless(glm_pw_p)
    nb1_nb2_mu1 <- NA
    
  nb1_nb2_mu2 <- NA
  nb1_nb2_effect <- NA
  nb1_nb2_sd_b1 <- NA
  nb1_nb2_pw_mu1 <- NA
  nb1_nb2_pw_mu2 <- NA
  nb1_nb2_pw_effect <- NA
  nb1_nb2_pw_sd_b1 <- NA

  fit_models <- c("lm", "gls", "lm_log", "qp", "nb1", "nb2", "nb1_nb2",
                  "nb1_pw", "nb2_pw", "nb1_pw_lrt", "nb2_pw_lrt", "nb1b", "nb2b", "mw")
  summary_table <- rbind(
    summary_table,
    data.table(
      "theta" = gen_theta,
      "gen_model" = gen_model,
      "n" = n,
      type = sim_type,
      "fit_model" = fit_models,
      "mu1" = c(lm_mu1, gls_mu1, lm_log_mu1, qp_mu1,
                nb1_mu1, nb2_mu1, nb1_nb2_mu1,
                nb1_pw_mu1, nb2_pw_mu1,
                nb1_pw_lrt_mu1, nb2_pw_lrt_mu1,
                nb1b_mu1, nb2b_mu1, mw_mu1),
      "mu2" = c(lm_mu2, gls_mu2, lm_log_mu2, qp_mu2,
                nb1_mu2, nb2_mu2, nb1_nb2_mu2,
                nb1_pw_mu2, nb2_pw_mu2,
                nb1_pw_lrt_mu2, nb2_pw_lrt_mu2,
                nb1b_mu2, nb2b_mu2, mw_mu2),
      "effect" = c(lm_effect, gls_effect, lm_log_effect, qp_effect,
                nb1_effect, nb2_effect, nb1_nb2_effect,
                nb1_pw_effect, nb2_pw_effect,
                nb1_pw_lrt_effect, nb2_pw_lrt_effect,
                nb1b_effect, nb2b_effect, mw_effect),
      "sd(b1)" = c(lm_sd_b1, gls_sd_b1, lm_log_sd_b1, qp_sd_b1,
                nb1_sd_b1, nb2_sd_b1, nb1_nb2_sd_b1,
                nb1_pw_sd_b1, nb2_pw_sd_b1,
                nb1_pw_lrt_sd_b1, nb2_pw_lrt_sd_b1,
                nb1b_sd_b1, nb2b_sd_b1, mw_sd_b1),
      "p < 0.05" = c(lm_pless, gls_pless, lm_log_pless, qp_pless,
                nb1_pless, nb2_pless, nb1_nb2_pless, 
                nb1_pw_pless, nb2_pw_pless,
                nb1_pw_lrt_pless, nb2_pw_lrt_pless,
                nb1b_pless, nb2b_pless, mw_pless)
    )
  )
  
}

summary_table_wide <- dcast(summary_table,
                            theta + gen_model + n + fit_model ~ type,
                            value.var = "p < 0.05")
summary_table_wide[type1 > 0.05, penalized_power := (1 - (1 - power))/sqrt(1 + abs(1 - type1/0.05))]

summary_table |>
  kable(digits = c(1,1,1,1,1,3,3,3,3,3,3)) |>
  kable_styling()

summary_table[, fit_model := factor(fit_model,
                                    levels = fit_models)]

heatmap_type1 <- summary_table[type == "type1"]
setnames(heatmap_type1, "p < 0.05", "type1")
heatmap_type1[, sim := paste(theta, gen_model, n, sep = "\n")]
heatmap_type1[, sim := factor(sim,
                                    levels = unique(sim))]
heatmap_type1[, fit_model := factor(fit_model,
                                    levels = fit_models)]

heatmap_power <- summary_table[type == "power"]
setnames(heatmap_power, "p < 0.05", "power")
heatmap_power[, sim := paste(theta, gen_model, n, sep = "\n")]
heatmap_power[, sim := factor(sim,
                                    levels = unique(sim))]
heatmap_power[, fit_model := factor(fit_model,
                                    levels = fit_models)]
sim_levels <- levels(heatmap_power$sim)


gg1 <- ggplot(data = heatmap_type1,
              aes(x = sim, y = fit_model, fill = type1)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue",
                       mid = "white",
                       high = "red",
                       midpoint = 0.05) +
  geom_text(aes(label = round(type1,3)), color = "black", size = 2) +
  labs(title = "Type 1",
       x = "Parameters",
       y = "Fit Model")

gg2 <- ggplot(data = heatmap_power,
              aes(x = sim, y = fit_model, fill = power)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#e5f5e0", # "#fee5d9"
                       high = "#238b45",
                       midpoint = median(heatmap_power[, power])) +
  geom_text(aes(label = round(power, 2)), color = "black", size = 2) +
  labs(title = "Power",
       x = "Parameters",
       y = "Fit Model")

# gg1
# gg2
plot_grid(gg1, gg2)
```

```{r combine-results_out}
balanced <- TRUE
if(balanced){
  unbalanced <- FALSE
}else{
  unbalanced <- TRUE
}
if(balanced){
  # unbalanced
  file1 <- readRDS("glm_3x_results_balanced 1000 seed 1.Rds")
  file2 <- readRDS("glm_3x_results_balanced 2000 seed 2.Rds")
  file3 <- readRDS("glm_3x_results_balanced 2000 seed 2.Rds")
  results_out <- rbind(file1, file2, file3)
  file_save <- "glm_3x_results_balanced.Rds"
}
if(unbalanced){
  # unbalanced
  file1 <- readRDS("glm_3x_results_unbalanced 2000 seed 1.Rds")
  file2 <- readRDS("glm_3x_results_unbalanced 3000 seed 2.Rds")
  results_out <- rbind(file1, file2)
  file_save <- "glm_3x_results_unbalanced.Rds"
}
#balanced

# resave
saveRDS(results_out, file_save)

```

```{r nb1-nb2-check}
# https://stats.stackexchange.com/questions/71519/when-do-poisson-and-negative-binomial-regressions-fit-the-same-coefficients
n_iter <- 50
set.seed(1)
file_path <- "glm_3x_nb1-nb2-check.Rds"
# variable parameters
model_list <- c("qp", "nb")
n_list <- c(6, 20)
theta_list <- c(1, 5)

parameter_matrix <- expand.grid(theta = theta_list,
                                model = model_list,
                                sample_size = n_list)


stats_labels <- c("qp_aic", "qp_unif", "qp_disp", "qp_xxx",
                  "nb1_aic", "nb1_unif", "nb1_disp", "nb1_xxx",
                  "nb2_aic", "nb2_unif", "nb2_disp", "nb2_xxx",
                  "nb1_pw_aic", "nb1_pw_unif", "nb1_pw_disp", "nb1_pw_xxx",
                  "nb2_pw_aic", "nb2_pw_unif", "nb2_pw_disp", "nb2_pw_xxx")
results_out <- data.table(NULL)

mag <- 1
mu_sim <- c(10^mag, 10^mag, 2*10^mag)
k <- length(mu_sim)


stats_matrix <- matrix(nrow = n_iter,
                       ncol = length(stats_labels))
colnames(stats_matrix) <- stats_labels

for(parameter_set in 1:nrow(parameter_matrix)){
  gen_theta <- parameter_matrix[parameter_set, "theta"]
  gen_model <- parameter_matrix[parameter_set, "model"]
  n <- parameter_matrix[parameter_set, "sample_size"]

  fd <- data.table(
    genotype = rep(c("WT", "KO", "TR"), each = n) |>
      factor(levels = c("WT", "KO", "TR"))
  )
  
  # nb var = mu + mu^2/theta
  # qp var = theta*mu
  # qp*mu = mu + mu^2/nb
  # qp = mu/mu + mu^2/nb
  # qp = 1 + mu/nb
  # if nb = 0.5 qp and mu = 10 then qp = 21
  # if nb = 2 qp and mu = 10 then qp = 6
  theta_nb <- gen_theta
  theta_qp <- 1 + mu_sim/theta_nb
  if(gen_model == "qp"){
    y_qp <- rqpois(n * k * n_iter,
                   mu = rep(mu_sim, each = n),
                   theta = theta_qp[1])
    y_mat <- matrix(y_qp, nrow = n * k, ncol = n_iter)
  }
  if(gen_model == "nb"){
    y_nb <- rnegbin(n * k * n_iter,
                    mu = rep(mu_sim, each = n),
                    theta = theta_nb)
    y_mat <- matrix(y_nb, nrow = n * k, ncol = n_iter)
  }

  for(iter in 1:n_iter){
    fd[, tumors := y_mat[, iter]]
    qp1 <- glm(tumors ~ genotype,
               family = quasipoisson(link = "log"),
               data = fd)
    nb1 <- glmmTMB(tumors ~ genotype,
                   family = nbinom1(link = "log"),
                   data = fd)
    nb2 <- glmmTMB(tumors ~ genotype,
                  family = nbinom2(link = "log"),
                  data = fd)
    aic_vals <- AIC(nb1, nb2)
    stats_matrix[iter, "nb1_aic"] <- aic_vals[1,2]
    stats_matrix[iter, "nb2_aic"] <- aic_vals[2,2]
    qp1_check <- ggcheck_the_glm(qp1, n_sim = 500)
    nb1_check <- ggcheck_the_glm(nb1, n_sim = 500)
    nb2_check <- ggcheck_the_glm(nb2, n_sim = 500)
    stats_matrix[iter, "qp_unif"] <- testUniformity(qp1_check)$statistic
    stats_matrix[iter, "nb1_unif"] <- testUniformity(nb1_check)$statistic
    stats_matrix[iter, "nb2_unif"] <- testUniformity(nb2_check)$statistic
    stats_matrix[iter, "qp_disp"] <- testDispersion(qp1_check)$statistic
    stats_matrix[iter, "nb1_disp"] <- testDispersion(nb1_check)$statistic
    stats_matrix[iter, "nb2_disp"] <- testDispersion(nb2_check)$statistic
  }
  results_out <- rbind(
    results_out,
    data.table(
      theta = gen_theta,
      model = gen_model,
      sample_size = n,
      type = "type1",
      stats_matrix
    )
  )
}

saveRDS(results_out, file_path)
results_out <- readRDS(file_path)

results_out[, aic_nb2_nb1 := nb2_aic - nb1_aic] # if nb1 better, than this will be positive
results_out[, unif_nb2_nb1 := nb2_unif - nb1_unif] # if nb1 better, than this will be positive
results_out[, unif_nb2_qp1 := nb2_unif - qp_unif] # if qp better, than this will be positive
results_out[, unif_nb1_qp1 := nb1_unif - qp_unif] # if qp better, than this will be positive
results_out[, disp_nb2_nb1 := nb2_disp - nb1_disp] # if nb1 better, than this will be positive
ggplot(data = results_out, # if nb1 better, than this will be positive
       aes(x = model,
           y = aic_nb2_nb1)) +
  geom_jitter(width = 0.2) +
  facet_grid(sample_size ~ theta)
ggplot(data = results_out, # if nb1 better, than this will be positive
       aes(x = model,
           y = unif_nb2_nb1)) +
  geom_jitter(width = 0.2) +
  facet_grid(sample_size ~ theta)
ggplot(data = results_out[sample_size == 20 & theta == 1], # if qp better, than this will be positive
       aes(x = model,
           y = unif_nb2_qp1)) +
  geom_jitter(width = 0.2)
ggplot(data = results_out[sample_size == 20 & theta == 1],
       aes(x = model,
           y = unif_nb1_qp1)) +
  geom_jitter(width = 0.2)
ggplot(data = results_out[sample_size == 20 & theta == 1], # if nb1 better, than this will be positive
       aes(x = model,
           y = disp_nb2_nb1)) +
  geom_jitter(width = 0.2)

results_out[, sim_id := .I]

```


```{r}
Tx=c('TS','TS','TS','TS','CT','CT','CT','CT','TS','TS','TS','TS','RL','RL','RL','RL','RT','RT','RT','RT','RL','RL','RT','RT','RT','RT','RL','RL','RL','RT','RT','RT','TS','TS','CT','CT','CT','CT','RL','RL','RL','RT','RT','RT','RT','CT','CT','CT','CT','CT','CT','TS','TS')
Bk= c('A','A','A','A','B','B','B','B','D','D','D','D','D','D','D','D','D','D','D','D','A','A','A','A','A','A','C','C','C','C','C', 'C','C','C','C','C','C','C','B','B','B','B','B','B','B','D','D','D','A','A','A','B','B')
Rv=c(2.08,2.08,2.52,3.42,2.8,5.57,2.53,3.69,1.55,1.45,3.98,3.19,2.3,2.09,2.26,2.1,3.21,2.99,2.11,2.09,1.64,1.74,1.66,6.41,1.86,2.71,1.83,0.86,2.37,1.05,1.37,2.08,1.09,1.44,0.6,1.24,3.32,1.34,1.86,4.54,2.7,2.5,4.93,2.85,3.42,2.77,2.71,4.11,5.29,2.16,3.15,4.58,2.89)
dat <- data.table(Tx, Bk, Rv)
lmm.ri <- lmer(Rv ~ Tx + (1 | Bk), data = dat)
lmm.ris <- lmer(Rv ~ Tx + (Tx | Bk), data = dat)
rmaov <- aov_4(Rv ~ Tx + (Tx | Bk),
               fun_aggregate = mean,
               data = dat)


contrast(emmeans(lmm.ri, specs = "Tx"), method = "revpairwise", adjust = "none")
contrast(emmeans(lmm.ris, specs = "Tx"), method = "revpairwise", adjust = "none")
contrast(emmeans(rmaov, specs = "Tx"), method = "revpairwise", adjust = "none")

VarCorr(lmm.ri)
VarCorr(lmm.ris)

lm1 <- lm(Rv ~ Tx, data = dat)
dat[, resid := residuals(lm1)]
dat_agg <- dat[, .(Rv = mean(Rv)), by = .(Tx, Bk)]
dat_agg_wide <- dcast(dat_agg, Bk ~ Tx, val.var = "Rv")
cor(dat_agg_wide[, .SD, .SDcols = c("A", "B", "C", "D")])
```

